---
title: Анализ работы
---

Здесь будут выкладываться текущие результаты ваших работ.




```{r,  echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
library(dplyr)
library(readxl)
library(ggplot2)
library(broom)
library(tidyr)


class <- read_xlsx("data/Classess_2024_biotech.xlsx", col_names = T)
# class <- class %>% filter(!is.na(Login)|!is.na(Group) )
class <- class %>% select(St_Mail, Login)


opts_chunk$set(echo = FALSE)

```


<!-- ############## Биологи ################# -->

# **Анализ тестов по материалам лекций**

Максимальное количество баллов для экзамена: 3%



```{r,  echo=FALSE, message=FALSE, warning=FALSE}

credits <- class %>% select(Login, St_Mail)

# Тест по Лекции 1
test_lecture_1 <- read_excel("data/Аутэкология (Экология для биоинженеров 2024)(1-12).xlsx")

test_lecture_1 <- test_lecture_1 %>% select(c(4,6))


names(test_lecture_1) <- c("St_Mail", "Score_lecture_1")


credits <- merge(credits, test_lecture_1, all.x = TRUE)



#Тест по Лекции 2

test_lecture_2 <- read_xlsx("data/Структура динамик типы популяционных групировок(Экология для биоинженеров 2024)(1-8).xlsx")


test_lecture_2 <- test_lecture_2 %>% select(4,6)
names(test_lecture_2) <- c("St_Mail", "Score_lecture_2")

credits <- merge(credits, test_lecture_2, all.x = TRUE)

# #Тест по Лекции 3


test_lecture_3 <- read_xlsx("data/Взаимодействие между организмами(1-11).xlsx")

test_lecture_3 <- test_lecture_3 %>% select(4,6)
names(test_lecture_3) <- c("St_Mail", "Score_lecture_3")

credits <- merge(credits, test_lecture_3, all.x = TRUE)

#
# #
# test_lecture_4 <- read_xlsx("data/Взаимоотношения организмов и популяций (Общая экология 2023)(1-98).xlsx")
# 
# test_lecture_4 <- test_lecture_4 %>% select(1,3)
# names(test_lecture_4) <- c("St_Mail", "Score_lecture_4")
# 
# credits <- merge(credits, test_lecture_4, all.x = TRUE)
# #


# test_lecture_5 <- read_xlsx("data/Конкуренция (Общая экология 2023)(1-89).xlsx")
# 
# test_lecture_5 <- test_lecture_5 %>% select(1,3)
# names(test_lecture_5) <- c("St_Mail", "Score_lecture_5")
# 
# credits <- merge(credits, test_lecture_5, all.x = TRUE)
# 
# 
# test_lecture_6 <- read_xlsx("data/Трофические связи (Общая экология 2023)(1-100).xlsx")
# 
# test_lecture_6 <- test_lecture_6 %>% select(1,3)
# names(test_lecture_6) <- c("St_Mail", "Score_lecture_6")
# 
# credits <- merge(credits, test_lecture_6, all.x = TRUE)
# 
# 
# 
# test_lecture_7 <- read_xlsx("data/Симбиозы (Общая экология 2023)(1-92).xlsx")
# 
# 
# test_lecture_7 <- test_lecture_7 %>% select(1,3)
# names(test_lecture_7) <- c("St_Mail", "Score_lecture_7")
# 
# credits <- merge(credits, test_lecture_7, all.x = TRUE)



#
#


# test_lecture_8 <- read_xlsx("data/Структура и динамика сообществ (Общая экология 2023)(1-87).xlsx")
# 
# test_lecture_8 <- test_lecture_8 %>% select(1,3)
# names(test_lecture_8) <- c("St_Mail", "Score_lecture_8")
# 
# credits <-  merge(credits, test_lecture_8, all.x = TRUE)



##########################
#Вывод общей таблицы с баллами

credits <- credits %>% filter(Login != "NA")

credits_sum <- 17 + 19 + 10
# + 10 + 8 + 10 + 10 + 5 + 7

credits_print <- credits %>% select(-St_Mail)

credits_print$Sum <- credits_print %>% select(-c("Login")) %>% rowSums(na.rm=TRUE)

credits_print$Credit_Sum <- credits_sum

credits_print$Proportion <- round(credits_print$Sum / credits_print$Credit_Sum, 2)

credits_print$Exam <- credits_print$Proportion * 3

# credits_print$Exam <- round(credits_print$Exam, 1) * 10 #умножаем на это число, так как от каждой из 8 лекций приходит 10/8 финальной оценки



```



**Состояние индивидуального счета студентов**
```{r, echo=F}

options(knitr.kable.NA = '-')

credits_print <- credits_print %>% filter(!is.na(Login)) %>% select(-Sum, -Credit_Sum)

kable(credits_print)


```




<!-- # **Анализ отчетов по самостоятельной работе № 1** -->


<!-- ```{r,  echo=FALSE, message=FALSE, warning=FALSE} -->

<!-- hw1 <- read_xlsx("data/Соответствие между организмом и средой, адаптации (Общая экология 2023)(1-98).xlsx") -->
<!-- hw1 <- hw1[c(1,3,4)] -->
<!-- names(hw1) <- c("St_Mail", "Score", "Add_Score") -->

<!-- # add_hw1 <- read.csv("data/Самостоятельная работа №1 Дополнительный вопрос.csv", header = T) -->
<!-- # names(add_hw1) <- c("Login", "add_score") -->
<!-- # -->
<!-- # add_hw1 <- add_hw1 %>% group_by(Login) %>% summarise(add_score = max(add_score)) -->
<!-- # -->
<!-- # # hw1[!(hw1$Login %in% add_hw1$Login), ] -->
<!-- # -->

<!-- # hw1_score <- class %>% select(St_Mail, Login) -->
<!-- # -->
<!-- # hw1_score <- merge(hw1_score, hw1, all.x = T) -->
<!-- # -->
<!-- # hw1_score <- merge(hw1_score, add_hw1, all.x = T) -->
<!-- # -->
<!-- # hw1_score$Sum <- hw1_score %>% select(Score, add_score) %>% rowSums(., na.rm = T) -->

<!-- hw1_score <- hw1 -->

<!-- hw1_score$Total <- 19 -->

<!-- hw1_score$Exam <- ifelse(is.na(hw1_score$Add_Score),  -->
<!--                          round((hw1_score$Score) / hw1_score$Total * 1.5, 1), -->
<!--                          round((hw1_score$Score + hw1_score$Add_Score) / hw1_score$Total * 1.5, 1)) -->

<!-- # hw1_score_print <- hw1_score %>% select(Login, Score, add_score, Sum, Exam) -->

<!-- hw1_score_print <- hw1_score -->

<!-- # kable(hw1_score_print, col.names = c("Login", "Основные вопросы", "Доп. вопр. 1", "Сумма",  "% от экзаменационной оценки")) -->

<!-- kable(hw1_score_print, col.names = c("Login", "Сумма","Доп. вопрос", "Всего вопросов",  "% от экзаменационной оценки")) -->


<!-- ``` -->

<!-- <!-- <br> -->
<!-- <!-- <br> -->


<!-- # **Анализ отчетов по самостоятельной работе № 2** -->


<!-- ```{r,  echo=FALSE, message=FALSE, warning=FALSE} -->

<!-- hw2 <- read_xlsx("data/Тест по  материалам самостоятельной работы №2 (Общая экология 2023)(1-83).xlsx") -->
<!-- hw2 <- hw2 %>% select(1, 3) -->
<!-- names(hw2) <- c("Login", "Score") -->


<!-- # add_hw1 <- read.csv("data/Самостоятельная работа №1 Дополнительный вопрос.csv", header = T) -->
<!-- # names(add_hw1) <- c("Login", "add_score") -->
<!-- # -->
<!-- # add_hw1 <- add_hw1 %>% group_by(Login) %>% summarise(add_score = max(add_score)) -->
<!-- # -->
<!-- # # hw1[!(hw1$Login %in% add_hw1$Login), ] -->
<!-- # -->

<!-- # hw1_score <- class %>% select(St_Mail, Login) -->
<!-- # -->
<!-- # hw1_score <- merge(hw1_score, hw1, all.x = T) -->
<!-- # -->
<!-- # hw1_score <- merge(hw1_score, add_hw1, all.x = T) -->
<!-- # -->
<!-- # hw1_score$Sum <- hw1_score %>% select(Score, add_score) %>% rowSums(., na.rm = T) -->

<!-- hw2_score <- hw2 -->

<!-- hw2_score$Total <- 23 -->

<!-- hw2_score$Exam <- round(hw2_score$Score / hw2_score$Total * 1.5, 1) -->

<!-- # hw1_score_print <- hw1_score %>% select(Login, Score, add_score, Sum, Exam) -->

<!-- hw2_score_print <- hw2_score -->

<!-- # kable(hw1_score_print, col.names = c("Login", "Основные вопросы", "Доп. вопр. 1", "Сумма",  "% от экзаменационной оценки")) -->

<!-- kable(hw2_score_print, col.names = c("Login", "Сумма", "Всего вопросов",  "% от экзаменационной оценки")) -->


<!-- ``` -->

<br>
<br>



## **Анализ контрольной работы № 1**

<!-- Максимальное количество баллов для экзамена: 3% -->

```{r,  echo=FALSE, message=FALSE, warning=FALSE}

cont1 <- read_excel("data/Контрольная работа № 1 (Экология для биоинженеров 2024)(1-12).xlsx")

cont1 <- cont1 %>% select(4, 6)

names(cont1) <- c("St_Mail", "Score")

# cont1_print <- merge(class, cont1 %>% select(-Name ), all.x = T ) %>% select(-St_Mail) %>% mutate(Exam = round(Score / 22 * 3, 1) )

cont1_print <- merge(class, cont1, all.x = T ) %>% select(-St_Mail) %>% mutate(Exam = round(Score / 18 * 3, 1) )


kable(cont1_print)


```




<!-- ## **Анализ контрольной работы № 2** -->


<!-- <!-- Максимальное количество баллов для экзамена 3% -->



<!-- ```{r,  echo=FALSE, message=FALSE, warning=FALSE} -->

<!-- # cont1 <- read_excel("data/Control_work_1_biotech.xlsx") -->

<!-- cont2 <- read_excel("data/Контрольная работа № 2 (Общая экология 2023)(1-106).xlsx") -->

<!-- cont2 <- cont2 %>% select(1:3) -->

<!-- names(cont2) <- c("St_Mail",  "Name", "Score") -->

<!-- cont2_print <- merge(class, cont2 %>% select(-Name ), all.x = TRUE ) %>% select(-St_Mail) %>% mutate(Exam = round(Score / 20 * 1.5, 1)) -->

<!-- kable(cont2_print) -->


<!-- ``` -->









<!-- ## **Оценки за семинары** -->

<!-- <!-- Максимальное количество баллов для экзамена 16% -->

<!-- ```{r warning = FALSE, message=FALSE} -->

<!-- library(googlesheets4) -->
<!-- sem <- read_sheet('https://docs.google.com/spreadsheets/d/1nOF5zamIBuOS99KluyJEwPnbvu0oUhx_uPu0q7O9Kx4/edit?usp=sharing') -->




<!-- # sem <- read_excel("data/Seminars_2023_biotech.xlsx", na = "NA") -->

<!-- sem <- sem %>% select(-c(Family, Name, Otch)) -->

<!-- sem_print <-  -->
<!--   merge(class, sem, all.x = TRUE ) %>%  -->
<!--   arrange(Group)%>%  -->
<!--   mutate(Exam = rowSums(.[4:ncol(.)], na.rm = T) * 3 ) %>%  -->
<!--   select(-St_Mail) -->


<!-- # %>% filter(Exam != 0) -->

<!-- ``` -->

<!-- ```{r } -->
<!-- kable(sem_print) -->

<!-- ``` -->





<!-- ## **Семинар-конференция № 2** -->


<!-- ```{r} -->

<!-- sem_2 <- read_excel("data/Conference_seminar_2.xlsx") -->

<!-- sem_2_print <- merge(class, sem_2) %>% select(-St_Mail) %>% mutate(Exam = Presentation + Presence + Speech + Bonus) -->

<!-- ``` -->

<!-- ```{r} -->
<!-- kable(sem_2_print) -->

<!-- ``` -->



<!-- ## **Результаты семинаров** -->

<!-- Семинары приносят в экзаменационную оценку 27% -->

<!-- **Коллеги!** -->

<!-- Оценки, которые вы видите ниже, это результат автоматической обработки базы, которую заполняют преподаватели после семинаров.  Проверяйте, пожалуйста, все ваши текущие оценки. Если вы видите, что вам что-то не проставлено, то срочно связывайтесь с соответствующим преподавателем. -->

<!-- Поверьте, у нас колоссальная нагрузка и мы не всегда успеваем внести оценки в ведомость. Контролируйте этот процесс, пожалуйста. -->



<!-- ```{r,  echo=FALSE, message=FALSE, warning=FALSE, eval=FALSE} -->

<!-- seminars <- read_excel("data/Семинары биологи 2022.xlsx") -->

<!-- names(seminars)[1:3] <- c( "Family", "Name", "Login") -->

<!-- seminars_print <- seminars %>% select(-Family, -Name) -->



<!-- seminars_print$Exam <- seminars_print %>% select(- c(Login, Group) ) %>% mutate(Sum = rowSums(., na.rm = T), Exam = Sum) %>% pull(Exam)  -->

<!-- seminars_print$Exam <- seminars_print$Exam*3 -->

<!-- kable(seminars_print) -->


<!-- ``` -->







<!-- ## **Итоговый счет группа биоинженеров** -->


<!-- ```{r warning = FALSE} -->

<!-- tests <- credits_print %>% select(Login, Exam) -->
<!-- names(tests) <- c("Login", "Тесты по лекциям") -->


<!-- cont1 <- cont1_print %>% select(Login, Exam) -->
<!-- names(cont1) <- c("Login", "Контрольная 1") -->



<!-- cont2 <- cont2_print %>% select(Login, Exam) -->
<!-- names(cont2) <- c("Login", "Контрольная 2") -->


<!-- sems <- sem_print %>% select(Login, Exam) -->

<!-- names(sems) <- c("Login", "Семинары" ) -->


<!-- d <- merge(tests, cont1, by = "Login", all.x = TRUE) -->
<!-- dd <- merge(d, cont2, by = "Login", all.x = TRUE) -->
<!-- final <- merge(dd, sems, by = "Login", all.x = TRUE) -->

<!-- names(final) <- c("Login", "Тесты по лекциям", "Контрольная 1", "Контрольная 2","Семинары" ) -->

<!-- Exam <- rowSums(final[,-1], na.rm = T) -->

<!-- final$Exam <- Exam -->

<!-- kable(final) -->

<!-- ``` -->



<!-- ## **Итоговый счет биологи 2023** -->



<!-- ```{r,  echo=FALSE, message=FALSE, warning=FALSE} -->
<!-- library(stringr) -->


<!-- d1 <- credits_print %>% select(Login, Exam) -->
<!-- d1$Exam <- round(d1$Exam, 2) -->


<!-- d2 <- cont1_print %>% select(Login, Exam) -->
<!-- d2$Exam <- round(d2$Exam, 2) -->



<!-- d3 <- cont2_print %>% select(Login, Exam) -->
<!-- d3$Exam <- round(d3$Exam, 2) -->


<!-- d4 <- hw1_score_print %>% select(St_Mail, Exam) -->
<!-- d4$Login <- word(d4$St_Mail, 1 ,sep = "\\@") -->
<!-- d4$Exam <- round(d4$Exam, 2) -->


<!-- d5 <- hw2_score_print %>% select(Login, Exam) -->
<!-- d5$Login <- word(d5$Login, 1 ,sep = "\\@") -->
<!-- d5$Exam <- round(d5$Exam, 2) -->


<!-- d6 <- sem_print %>% select(Login, Exam) -->
<!-- d6$Exam <- round(d6$Exam, 2) -->


<!-- Results <-  -->
<!--   merge(d1, d2, by = "Login", all = T) %>%  -->
<!--   merge(., d3, by = "Login", all = T) %>%  -->
<!--   merge(., d4, by = "Login", all = T) %>%   -->
<!--   merge(., d5, by = "Login", all = T) %>%   -->
<!--   merge(., d6, by = "Login", all = T) -->


<!-- names(Results) <- c("Login", "Lecture_test", "Control_1", "Control_2", "St_Mail", "Home Work 1", "Home Work 2", "Seminars") -->

<!-- Results <- -->
<!--   Results %>%  -->
<!--   select(-St_Mail) -->




<!-- Results_print <- Results -->

<!-- Results_print$Exam <- round(apply(Results[,-1], MARGIN = 1, FUN = function(x) sum(x, na.rm = T) ), 1) -->

<!-- Results_print <- Results_print %>% filter(!is.na(Login)) %>% filter(Login != "NA") -->


<!-- # # Код для вывода суммарных оценок с именами. -->
<!-- # class <- read_xlsx("data/Classess_2022_biology.xlsx", col_names = T) -->
<!-- # -->
<!-- # final_results <- class %>% select(Family, Name, Otch, Login) %>% merge(., Results_print, all.x = T) -->
<!-- # -->
<!-- # write.table(final_results, "clipboard", sep = "\t", row.names = F) -->

<!-- ``` -->

<!-- ```{r} -->

<!-- options(knitr.kable.NA = '-') -->
<!-- kable(Results_print) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- # Результаты в сумме для создания файла-ведомости экзамена -->

<!-- class <- read_xlsx("data/Classess_2023_biology.xlsx", col_names = T) -->
<!-- # class <- class %>% filter(!is.na(Login)|!is.na(Group) ) -->
<!-- class <- class %>% select(St_Mail, Login, Family, Name, Otch ) -->
<!-- res <- merge(class, Results_print) -->

<!-- write.table(res, "data/results_for_examen.csv", sep = ";", row.names = F, fileEncoding = "UTF-8", dec = "," ) -->

<!-- ``` -->


