---
title: Материалы для подготовки к экзамену
---

## Что будут спрашивать на экзамене

Каждый студент должен будет ответить на два вопроса. Первый вопрос - теоретический (см. ниже). Второй вопрос - задача, решение которой потребует умения оперировать теоретическим материалом.


**Использование справочных материалов в экзаменационной аудитории будет запрещено.**  

Список теоретических вопросов (именно они и будут предложены на экзамене)

**Восклицательным знаком (!) помечены те вопросы, ответы на которые были даны на семинарах или в литературе, рекомендованной для самостоятельного изучения (самостоятельные работы №№ 1, 2, 3)**

1.Надорганизменные живые системы.      
2.Среда обитания. Пространственная структура среды обитания. Понятие экологического фактора.   
3.Действие экологического фактора. Причины образования купола толерантности. Витальное и сигнальное действие факторов.   
4.Закон Либиха и Закон Шелфорда.   
5!.Эволюционный процесс и его роль в формировании приспособленности организмов к среде обитания. Экотипы и физиологические расы    
6.Эврибионты и стенобионты.    
7!.Изменение реакции организмов на действие экологического фактора в пространстве и времени. Ритмы в активности организмов: Циркадные и лунные ритмы.     
8.Классификации экологических факторов.    
9!.Экологическое действие света (фотопериодизм)    
10!.Экологическое действие света (сциофиты и гелиофиты)   
11!.Экологическое действие температуры.    
12.Эктотермы и эндотрмы. Правило суммы эффективных температур.     
13.Экологическое действие солености. Осмоконформеры и осморегуляторы.    
14.Ресурсы и их отличие от других факторов среды.    
15.Унитарные и модулярные организмы и особенности их связи с окружающей средой.    
16.Методы определения численности популяционных группировок.    
17.Рождаемость и смертность, как основные популяционные параметры    
18.Эмиграция и иммиграция и их роль в процессах, протекающих в популяциях.    
19.Типы популяционных группировок.    
20.Пространственная структура популяционных группировок.    
21.Половая структура популяций. Определение пола у разных организмов.    
22.Роль биотических и абиотических факторов в формировании половой структуры популяций.    
23.Циклические изменения в половой структуре популяций.    
24.Возрастная структура популяции.Кривые выживания.Аномалии в возрастной структуре популяций.    
25.Основное уравнение динамики численности популяции.    
26.Закон Мальтуса. Экспоненциальная модель роста численности популяции.    
27.Модель ограниченного роста численности популяции. Модель Ферхлюста. Понятие емкости среды. Динамика первого и второго порядка.    
28.r- и K-стратегии. Равновесные и оппортунистические популяции. Характерные признаки r- и K-отбора.
29.Классификация стратегий видов Раменского-Грайма    
30.Циклические изменения численности популяции и их причины.    
31.Классификация симфизиологичских связей    
32.Классификация взаимоотношений по результату взаимодействий.    
33.Аменсализм и смежные явления     
34.Протокооперация и смежные явления    
35.Гнездовой паразитизм и смежные явления    
36.Cинойкия и смежные явления.    
37.Функциональная классификация организмов-потребителей.    
38.Теория оптимального фуражирования.    
39.Поведение хищников в пятнистом местообитании. Теорема о предельном значении.    
40.Динамика численности популяций потребителя (хищника) и биоресурса (жертвы).    
41.Эффект Олли.     
42.Феномен каннибализма.    
43.Экологическая ниша по Элтону. Гильдии.    
44.Две формы конкуренции: прямая и эксплуатационная.      
45.Внутривидовая конкуренция. Самоизреживание и аутотоксичность у растений.     
46.Межвидовая конкуренция и теория экологической ниши.     
47.Экологическая ниша по Хатчинсону. Фундаментальная и реализованные ниши.     
48.Модель экологической лицензии.     
49.Принцип конкурентного исключения. Динамика популяций конкурирующих видов.     
50.Особенности конкурентных взаимоотношений в растительных сообществах     
51.Экологическая диверсификация. Смещение признаков.      
52.Парадокс планктона     
53.Влияние межвидовой и внутривидовой конкуренции на место видов в экосистеме.       
54.Понятие симбиоза. Среда I и II порядков в симбиозах.       
55.Стратегии симбионтов и хозяев в становлении разных типов симбиозов.      
56.Мутуалистический симбиоз     
57.Комменсалистический симбиоз      
58.Паразитический симбиоз и его разновидности      
59.Адаптации паразитов, направленные на повышение притока энергии со стороны хозяина.      
60.Адаптации паразитов, направленные на снижение негативного влияния со стороны хозяина.      
61.Адаптации паразитов, направленные на повышение вероятности заражения следующего хозяина.      
62.Паразитарные системы и роль паразитов в сообществах       
63.Концепция экосистемы. Соотношение понятий экосистема и биогеоценоз.      
64!.Автотрофный и гетеротрофный компоненты экосистемы, их пространственное и временнóе разделение.    
65.Структура экосистемы: продуценты, консументы, редуценты.      
66.Поток энергии в экосистеме. Пищевые цепи и пищевые сети.     
67!.Биогеохимические циклы (на примере цикла углерода). Обменный и резервный фонды биогеохимических циклов.      
68.Классификация видов по их влиянию на свойства и структуру сообщества.      
69.Видовое разнообразие сообществ. Видовое разнообразие и нарушения сообществ      
70!.Изменения в экосистемах: аллогенные и автогенные изменения.      
71!.Cукцессии и их струкутра. Первичная и вторичная сукцессия.      
72!.Флуктуации и их разнообразие.      
73.Экосистемный и популяционный подход в экологии.      
74!.Экологические ниши в растительном мире        
75!.Жизненные формы животных и растений. Жизненные формы по Раункиеру.     
76.В чём сходство и в чём различие понятий «хищник», «детритофаг» и «редуцент»?      
77.Автотрофные и гетеротрофные экосистемы.     
78.Гетеротрофные антропогенные экосистемы     
79!.Биологическая продуктивность экосистем      
80!.Круговороты органического вещества в водных и наземных экосистемах     
81.Экологические пирамиды и их разнообразие     
82!.Агроэкосистемы и их отличия от естественных фотоавтотрофных экосистем.     
83.Эксперимент «Биосфера 2» и причины его остановки.      
84.Суть и критика теории «Моноклимакса» Ф. Клеменса      
85.Адвентивные и инвазионные виды       
86!.Основные биомы суши, их площадь и продуктивность.       




<!-- ## Темы, которые выносятся на экзамен {.smaller}  -->

<!-- **Внимание! Приведенные ниже формулировки не являются фрмулировками вопросов в билетах.**  -->

<!-- <!-- Материалы будут открыты позднее          --> 

<!-- 1.  Область компетенции экологии.   Надорганизменные живые системы. -->
<!-- 2.  Разделы экологии и их задачи -->
<!-- 3.  Среда обитания.   Понятие экологического фактора.   Пространственная структура среды обитания. -->
<!-- 4.  Уровень благосостояния организма и его измерение. -->
<!-- 5.  Действие экологического фактора.   Причины образования купола толерантности.   Закон Либиха, закон Шелфорда -->
<!-- 6.  Экотипы и физиологические расы, связь с эволюционным процессом. -->
<!-- 7.  Эврибионты и стенобионты. -->
<!-- 8.  Изменение реакции организмов на действие экологического фактора в пространстве и времени. -->
<!-- 9.  Ритмы в активности организмов: Циркадные и лунные ритмы. -->
<!-- 10.  Совместное действие нескольких факторов.   Реакция организмов на одновременное действие нескольких факторов: ведущие и лимитируемые факторы. -->
<!-- 11.   Классификации экологических факторов. -->
<!-- 12.  Витальное и сигнальное действие факторов. -->
<!-- 13.  Экологическое действие света (фотопериодизм) -->
<!-- 14.  Экологическое действие температуры.   Эктотермы и эндотрмы.   Правило суммы эффективных температур. -->
<!-- 15.  Экологическое действие солености.   Осмоконформеры и осморегуляторы. -->
<!-- 16.  Ресурсы и ох отличие от других факторов среды. -->
<!-- 17.  Уровни действия абиотических факторов (особи, популяции, сообщества, экосистемы). -->
<!-- 18.  Унитарные и модулярные организмы. -->
<!-- 19.  Методы определения численности популяционных группировок. -->
<!-- 20.  Фундаментальные параметры популяционных группировок ( Рождаемость, смертность, эмиграция, иммиграция, площадь популяции). -->
<!-- 21.  Типы популяционных группировок. -->
<!-- 22.  Пространственная структура популяционных группировок. -->
<!-- 23.  Половая структура популяций.   Определение пола у разных организмов.    Аномалии в половой структуре.   Циклические изменения в половой структуре. -->
<!-- 24.  Возрастная структура популяции: проблема определения возраста, кривые выживания, аномалии в возрастной структуре. -->
<!-- 25.  Основное уравнение динамики численности.  Удельная рождаемость и удельная смертность.   Мальтузианский параметр. -->
<!-- 26.  Закон Мальтуса.   Экспоненциальная модель роста численности популяции. -->
<!-- 27.  Модель ограниченного роста численности популяции .   Понятие емкости среды.   Модель хаотического колебания численности.   Динамика первого и второго порядка -->
<!-- 28.  r- и K-стратегии.   Равновесные и оппортунистические популяции.   Характерные признаки r- и K-отбора. -->
<!-- 29.  Классификация стратегий видов Раменского-Грайма -->
<!-- 30.  Циклические изменения численности популяции и их причины. -->
<!-- 31.  Причины долговременных колебаний в численности популяций. -->
<!-- 32.  Классификация симфизиологичских связей -->
<!-- 33.  Классификация взаимоотношений по результату взаимодействий. -->
<!-- 34.  Аменсализм и смежные явления -->
<!-- 35.  Протокооперация и смежные явления -->
<!-- 36.  Гнездовой паразитизм и смежные явления -->
<!-- 37.  Cинойкия и смежные явления. -->
<!-- 38.  Функциональная классификация организмов-потребителей. -->
<!-- 39.  «Гонка вооружений» хищников и жертв. -->
<!-- 40.  Теория оптимального фуражирования. -->
<!-- 41.  Динамика численности популяций потребителя (хищника) и биоресурса (жертвы). -->
<!-- 42.  Функциональная реакция хищников. -->
<!-- 43.  Ресурсы и их влияние на организм. -->
<!-- 44.  Эффект Олли. -->
<!-- 45.  Феномен каннибализма. -->
<!-- 46.  Экологическая ниша по Элтону.   Гильдии. -->
<!-- 47.  Экологическая ниша по Хатчинсону. -->
<!-- 48.  Две формы конкуренции: прямая и эксплуатационная. -->
<!-- 49.  Внутривидовая конкуренция.   Явление территориальности.   Теория агрессии К.  Лоренца.   Иерархические социальные структуры у животных.   Самоизреживание и аутотоксичность у растений. -->
<!-- 50.   Межвидовая конкуренция.   Фундаментальная и реализованная ниши.   Экологическая лицензия. -->
<!-- 51.  Принцип конкурентного исключения.   Динамика популяций конкурирующих видов. -->
<!-- 52.  Экологическая диверсификация.   Смещение признаков.   Парадокс планктона -->
<!-- 53.  Причины и последствия расхождения ниш.   Влияние межвидовой и внутривидовой конкуренции на место видов в экосистеме. -->
<!-- 54.  Понятие симбиоза.   Среда I и II порядков. -->
<!-- 55.  Стратегии симбионтов и хозяев в становлении разных типов симбиозов. -->
<!-- 56.  Мутуалистический симбиоз -->
<!-- 57.  Комменсалистический симбиоз -->
<!-- 58.  Паразитический симбиоз и его разновидности -->
<!-- 59.  Особенности паразитов, направленные на повышение притока энергии со стороны хозяина. -->
<!-- 60.  Адаптации паразитов, направленные на снижение негативного влияния со стороны хозяина. -->
<!-- 61.  Адаптации паразитов, направленные на повышение вероятности заражения следующего хозяина. -->
<!-- 62.  Паразитарные системы и роль паразитов в сообществах -->
<!-- 63.  Внутривидовые симбиозы -->
<!-- 64.  Концепция экосистемы. -->
<!-- 65.  Соотношение понятий экосистема и биогеоценоз. -->
<!-- 66.  Автотрофный и гетеротрофный компоненты экосистемы, их пространственное и временнóе разделение. -->
<!-- 67.  Структура экосистемы: продуценты, консументы, редуценты. -->
<!-- 68.  Поток энергии в экосистеме.   Пищевые цепи и пищевые сети. -->
<!-- 69.  Биогеохимические циклы.   Обменный и резервный фонды биогеохимических циклов. -->
<!-- 70.  Классификация видов по их влиянию на свойства и структуру сообщества. -->
<!-- 71.  Видовое разнообразие сообществ -->
<!-- 72.  Видовое разнообразие и нарушения сообществ -->
<!-- 73.  Изменения в экосистемах: аллогенные и автогенные изменения. -->
<!-- 74.  Cукцессии и их струкутра.   Биоэнергетика развития экосистемы.   Изменения в характере пищевых цепей, замыкание биогеохимических циклов.   Первичная и вторичная сукцессия. -->


## Опорный глоссарий {.smaller}

В опорном глоссарии приведены те термины, которые так или иначе мелькали в этом курсе. 

Если вы можете описать, что кроется за всеми этими понятиями, то вы почти готовы к экзамену!

```{r, echo=FALSE}
library(knitr)
terms <- read.csv("data/glossary.csv", header = TRUE)
kable(paste(1:nrow(terms),". ", terms$Term), col.names = "Термины")
```


