---
title: Материалы для самостоятельной работы
---

Экология очень разнообразна! На лекциях мы разберем лишь краткую выжимку из того, что развивается в рамках этого куста дисуиплин. Поэтому, если вы хотите углубить свои знания, можно самостоятельно освоить дополнительные части этого курса. 

<!-- Это опциональная часть, за нее не начисляются накопительные баллы, но... самое главное ведь не в них, а в том, что остается в голове.  -->


## Самостоятельная работа №1

Первая самостоятельная работа посвящена **эволюционной базе** и **соответствию между организмами и средой**.

Вам предстоит самостоятельно изучить источники по этой теме и ответить на вопросы, которые будут предложены в тесте. Однако не торопитесь сразу проходить тест. Количество попыток ограничено одной. Поэтому лучше сначала прочитайте источники, которые предложены для ознакомления (см. ниже).



**Минимальный набор источников, обязательных для изучения**

- Бигон, М., Харпер, Дж., Таунсенд, К. Экология. Особи, популяции и сообщества. М.: Мир, 1989, **глава 1**.

Скачать книгу можно, пройдя по этой ссылке

https://drive.google.com/file/d/12jDdpfPV2Rnf4PKt0g3PuqPXKEUljSIW/view?usp=sharing



- Smith, R. L., Smith, T. M. Elements of ecology. - 2012. **Chapter 5. ECOLOGICAL GENETICS: ADAPTATION AND NATURAL SELECTION**

Скачать книгу можно, пройдя по этой ссылке (Большой объем!)

https://drive.google.com/file/d/1_aIEjvUMst1fAdTB60k9wnzxdsKb3Bm9/view?usp=sharing


- Бродский А.К. Биоразнообразие. М.: Изд. центр «Академия», 2012, **глава 2**. (книгу надо взять в библиотеке факультета)


Дополнительные источники

- Чернова Н.М., Былова А.М. Общая экология. Электронный учебник. **Глава 2**. (http://ekolog.org/books/26/)
- Begon, M., Townsend, C. R., & Harper, J. L. (2006). Ecology: from individuals to ecosystems. **Chapter 4**.

- Не забывайте про **Википедию** и прочие ресурсы Сети!



*Вопросы для самоконтроля*

1.Как оценивается большая или меньшая приспособленность организма к условиям среды?    
2.Что такое нунатаки?    
3.Как влияет изоляция территории / акватории на биоразнообразие?    
4.Влияет ли изоляция на среднюю экологическую амплитуду видов?    
5.В чем разница между параллелизмом и конвергенцией?    
6.Что такое дивергенция, как она возникает?   
7.Что такое экологические гильдии?    
8.Может ли принадлежность к одной гильдии приводить к конвергенции?    
9.Может ли конвергенция случиться у видов разных гильдий?    
10.Что такое Жизненные формы растений?    
11.Что такое классификация жизненных форм по Раункиеру?    
12.С чем связано морфологическое разнообразие видов, сообитающих в одном сообществе?    
13.Что такое экологические группы?    
14.Что такое экотипы?    
15.Чем вызван полиморфизм в популяциях?    
16.Чем поддерживавется полиморфизм в популяциях?    
17.Каким образом достигается соответствие между организмом и средой, если среда – это другой организм?    
18. Какие формы естественного отбора вы знаете?    
19. Что такое генетический полиморфизм?    
20. Какие явления могут приводить к изменениям в структуре генофонда популяций?    
21. Что регулирует закон Харди-Вайнберга?     


**Опорный глоссарий:**    
Адаптация; Адаптивная радиация; Генетический дрифт; Генетический полиморфизм; Генотип; Гильдия; Гомология; Движущий отбор; Дизруптивный отбор; Естественный отбор; Жизненная форма (растений); Закон Харди-Вайнберга; Клинальная изменчивость; Конвергенция; Коэволюция; Нунатаки; Параллелизм; Полиморфизм; Поток генов; Приспособленность; Стабилизирующий отбор; Фенотип; Фенотипический полиморфизм; Частота аллели; Частота генотипа; Экотип;





## Самостоятельная работа №2


### Многообразие жизненных циклов и Биогеохимические циклы

<!-- Для оценки самостоятельной работы Вам предстоит пройти тест (заполнить гугл-форму). Перед тем как начать прохождение теста, посмотрите на вопросы приведенные ниже. Если вы уже понимаете, как на них отвечать, то самое время начать тестирование. -->

<!-- **Внимание!** -->
<!-- Тест будет открыт с 20 октября по 30 октября (мягкий дедлайн), в период после 30 октября за правильные ответы будет начисляться только половина балла.  -->

**Минимальный набор источников, обязательных для изучения**

**Многообразие жизненных циклов**

- Бигон, М., Харпер, Дж., Таунсенд, К. Экология. Особи, популяции и сообщества. М.: Мир, 1989, **глава 14**.

Второй том можно скачать здесь
https://drive.google.com/file/d/1BMRC-PZy2gUmL2DtUessL5o2tHT36rSs/view?usp=sharing

- Бродский А.К. Биоразнообразие. М.: Изд. центр «Академия», 2012, **глава 8**.

- Begon, M., Townsend, C. R., & Harper, J. L. (2006). Ecology: from individuals to ecosystems. **Chapter 14**.


*Очень рекомендуется прочитать*

- Smith, R. L., Smith, T. M. Elements of ecology. - 2012. **Chapter 10 Life History**

Здесь все описано лучше и проще.




**Биогеохимические циклы**

- [Одум Ю. Экология: в двух томах. М.: Мир, 1986. Т. 1. 328 с. **Глава 4**](Literature//Ю.Одум - Экология (1) .djvu)

- [Бигон М., Харпер Дж., Таунсенд К. Экология. Особи, популяции и сообщества: в двух томах. М.: Мир, 1989. Т. 2. 477 с. **Глава 17.5**](Literature/bigon_m___harper_dzh___taunsend_k__yekologija__osobi__populj(2).djvu)

- [Еськов К.Ю. История Земли и жизни на ней. М.: Изд-во НЦ ЭНАС, 2004. 312 с. **Глава 4**](Literature/eskov2008_udivit_paleontol.djvu)



*Очень рекомендуется прочитать*
Smith, R. L., Smith, T. M. Elements of ecology. - 2012. **Chapter 23 Biogeochemical Cycles**

Очень рекоментуется посмотреть видео:
- [Видеозапись лекции К. Ю. Еськова, посвященной происхождению жизни](https://www.youtube.com/watch?v=ylAOzdXEbaA)




- Не забывайте про Википедию и прочие ресурсы Сети!



*Вопросы для самоконтроля*   
1.Что такое репродуктивные траты? Как их измерить?   
2.Какие бывают отклонения от теоретически ожидаемых эффектов r- / K-отбора.    
3.Есть ли какая-либо связь между цикличностью размножения и интенсивностью заботы о потомстве?    
4.Что такое остаточная репродуктивная ценность и как она меняется с возрастом при разном состоянии популяции?    
5.Как репродуктивная ценность связана с качеством питания особи?    
6.Какие демографические эффекты может иметь «отсрочка размножения»?    
7.Каково соотношение типов естественного отбора (r- / K-отбор) и жизненных стратегий Раменского-Грайма?   
8.Каковы условия r-отбора?   
9.Каковы условия К-отбора?        
10.Аллометрические зависимости: как они влияют на рождаемость и смертность?    

*Опорный глоссарий:*    
K-Стратеги, r-селективная среда, r-Стратеги, Выживаемость, Жизненные циклы, Изолированные местообитания, Классификация Грайма., Конкуренты, К-селективная среда, Моноцикличность, Неизменные местообитания, Непрерывные местообитания, Остаточная репродуктивная ценность, Плодовитость, Полицикличность, Пятнистые местообитания, Размеры, Размножение, Репродуктивная ценность, репродуктивное усилие, Рудералы, Сезонные местообитания, Скорость роста и развития, Сома, Стресс-толеранты, Текущий репродуктивный выход, Эфемерные местообитания




*Вопросы для самоконтроля*

Применим ли принцип дарвиновского естественного отбора для неживых (химических) систем?  

Что такое автокаталитические циклы?   

Каковы стадии абиогенного происхождения живых систем, согласно биогеохимической концепции происхождения жизни?   

Что такое блочная модель круговорота?   

Как устроены круговороты основных элементов, необходимых для существования живых систем (C, N, P, S, O, H)?   

Что такое первичная и вторичная продукция?  

Что такое валовая и чистая первичная продукция?  




*Опорный глоссарий:*

Абиогенез; Автокаталитические циклы; Автотрофы; Азотфиксирующие бактерии; Биогеохимические циклы; Блочная модель круговорота; Валовая продукция; Вторичная продукция; Гетеротрофы; Денитрифицирующие бактерии; Дыхание; Консументы; Коэффициент рециркуляции; Нитратные бактерии; Нитритные бактерии; Обменный фонд круговорота; Протометаболические системы; Редуценты; Резервный фонд круговорота; Цикл азота; Цикл серы; Цикл углерода; Цикл фосфора; Чистая первичная продукция; Эвтрофикация; Энтропия



*Вопросы для самоконтроля*

Применим ли принцип дарвиновского естественного отбора для неживых (химических) систем?  

Что такое автокаталитические циклы?   

Каковы стадии абиогенного происхождения живых систем, согласно биогеохимической концепции происхождения жизни?   

Что такое блочная модель круговорота?   

Как устроены круговороты основных элементов, необходимых для существования живых систем (C, N, P, S, O, H)?   

Что такое первичная и вторичная продукция?  

Что такое валовая и чистая первичная продукция?  




*Опорный глоссарий:*

Абиогенез; Автокаталитические циклы; Автотрофы; Азотфиксирующие бактерии; Биогеохимические циклы; Блочная модель круговорота; Валовая продукция; Вторичная продукция; Гетеротрофы; Денитрифицирующие бактерии; Дыхание; Консументы; Коэффициент рециркуляции; Нитратные бактерии; Нитритные бактерии; Обменный фонд круговорота; Протометаболические системы; Редуценты; Резервный фонд круговорота; Цикл азота; Цикл серы; Цикл углерода; Цикл фосфора; Чистая первичная продукция; Эвтрофикация; Энтропия








## Дополнительное задание к самостоятельной работе № 2

По мотивам проработанной литературы (см. список литературы в основном задании) вам предлагается придумать вопросы в стиле тех, что используются в тестах. За каждый вопрос, который преподавательский коллектив сочтет удачным, вы получите по одному дополнительному баллу к общей оценке по самостоятельной работе № 2. То есть итоговая оценка за самостоятельную работу №2 может быть больше 1.


**Требования к вопросам**

1. Вопрос должен иметь отношение к материалу, изложенному в предложенной для ознакомления литературе.

2. Вопрос должен быть построен по типу "множественного выбора", то есть подразумевается много правильных ответов.

3. К присланному вопросу должны быть приложены варианты правильных и неправильных ответов (чем больше, тем больше шансов, что вопрос будет принят).

4. К каждому вопросу необходимо приложить ссылку на страницы в книге, где содержится информация, лежащая в основе вопроса.

Все материалы необходимо прислать на адрес В. М. Хайтова в период с 20.10.2020 по 31.10.2020.




<!-- $$ -->
<!-- \frac{Real + Add}{Max}\times 3 \% -->
<!-- $$ -->

<!-- где -->

<!-- -$Real$ - сумма баллов на Stepik -->
<!-- -$Max$ - максимальное количество баллов на Stepik -->
<!-- -$Add$ - дополнительные баллы, полученные за вопросы. -->



