---
title: Курс "Общая экология"
description: Материалы и объявления 
---

<style type="text/css">

body{ /* Normal  */
      font-size: 12px;
  }
td {  /* Table  */
  font-size: 12px;
}
h1.title {
  font-size: 18px;
  color: DarkBlue;
}
h1 { /* Header 1 */
  font-size: 16px;
  color: DarkBlue;
}
h2 { /* Header 2 */
    font-size: 16px;
  color: DarkBlue;
}
h3 { /* Header 3 */
  font-size: 12px;
  font-family: "Times New Roman", Times, serif;
  color: DarkBlue;
}
code.r{ /* Code block */
    font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 12px;
}
</style>


 
## О курсе
Современная биология у многих ассоциируется с изучением молекулярных основ жизни, однако на практике одной из центральных тенденций в развитии естествознания, несомненно, является познание организации и функционирования *надорганизменных* систем, относящихся к области компетенции экологии. В настоящий момент трудно говорить о какой-то единой науке «экологии», под этим термином кроется целый куст дисциплин. Поэтому курс «*Общая экология*» направлен, в первую очередь, на рассмотрение арсенала подходов, методов и принципов формулировок гипотез при изучении систем, включающих в себя в качестве первичных элементов организмы, популяции, сообщества и среду их существования.

### Цель и задачи курса
Главная цель курса - знакомство студентов не столько с огромным набором фактических данных, накопленных в экологических исследованиях, а, скорее, с методологией экологических исследований. 

**К числу главных задач курса мы относим**    
- Выработку навыков представления изучаемых явлений в системной форме и отражения полученных знаний в форме моделей.     
- Выработку навыков самостоятельного поиска информации, связанной с экологическими исследованиями, и ее критического осмысления.    
- Знакомство с наиболее разработанными обобщениями в области аутэкологии, популяционной биологии и синэкологии.    
- Знакомство с подходами и методами, используемыми в реальных экологических исследованиях.   


<!-- <!-- Версия для биологов --> 

<!-- ## Расписание и контакты -->

<!-- Лекции: с 4 сентября по две пары в **дистанционном режиме**. Лекции будут проходить в системе MS Teams  и ZOOM, администрирование курса будет проводиться с применением системы MS Teams. -->

<!-- О расписании семинаров объявим дополнительно -->

<!-- Лекторы: -->

<!-- - Хайтов Вадим Михайлович - polydora[]rambler.ru -->
<!-- - Тиходеева Марина Юрьевна - marinaur[]list.ru -->

<!-- Инструкторы семинаров: -->

<!-- - Мирин Денис Моисеевич (каф. Геоботаники) -->
<!-- - Мельницкий Станислав Игоревич (каф. Энтомологии) -->
<!-- - Чернова Елена Николаевна (каф. Прикладной экологии) -->
<!-- - Крапивин Владимир Александрович (каф. Зоологии беспозвоночных) -->
<!-- - Копцева Елена Михайловна (каф. Геоботаники) -->
<!-- <!-- - Кучеров Дмитрий Александрович (каф. Энтомологии) --> -->
<!-- - Гончар Анна Георгиевна (каф. Зоологии беспозвоночных) -->
<!-- - Иванов Михаил Валерьевич (Каф. Гидробиологии и ихтиологии) -->
<!-- - Ольга Валерьевна Князева (каф. Зоологии беспозвоночных) -->


<!-- Подготовка тестов и обслуживание сайта -->
<!-- - Вадим Михайлович Хайтов -->
<!-- - Ольга Валерьевна Князева -->

<!-- ## Структура курса, задания, дедлайны и оценки -->

<!-- Курс состоит из трех частей, реализуемых в два этапа. -->

<!-- **Этап 1** (первые 6 недель + 1 в резерве). -->

<!-- 1.Лекции -->
<!-- 2.Самостоятельная работа -->

<!-- **Этап 2** (7 недель) -->
<!-- 3.Семинары -->



<!-- **Оценки** -->
<!-- Политика курса направлена на использование накопительной системы, в которой  дробные оценки накапливаются студентом за все время прохождения курса. Финальная оценка за курс (которая пойдет в ведомость) складывается из нескольких частей. -->


<!-- 1. *Оценки за тесты, оценивающие освоение материалов лекций*. Задача этих тестов - привлечение студентов к внимательной работе с лекционным материалом, стимуляция посещения лекций и создание основы для постепенного освоения материалов. Эти оценки производятся на основе тестов, которые будут размещены на платформе Ms Teams. За сутки до начала очередной лекции будет открыт тест по материалам **предыдущих** лекций. Тест будет закрыт одновременно со временем начала текущей лекции. -->


<!-- 2. *Оценки за самостоятельную работу*. Эти оценки будут выставлены за задания, связанные с самостоятельным изучением литературных источников. Всего будет предложено изучить три темы, каждая из которых будет завершаться тестом, состоящим из задач, решение которых требует знания осовенной литературы. -->

<!-- 3.*Оценки за контрольные работы*. Всего будет две контрольные работы, которые будут проходить в формате online тестов, размещенных на платформе MS Teams. Каждый тест будет открыт для прохождения в определенный, согласованный с курсом, день. Студенты смогут его проходить в любом удобном для них месте, но только в течение 2 часов с момента начала тестирования. -->

<!-- 4.*Оценки за семинары*. Посещение каждого семинара принесет один балл в накопление, но стоимость этих баалов достстаочно высока (см. таблицу ниже). По итогам семинаров студенты, активно работающие на занятиях, могут получить дополнительнo 0.5 балла. Преподаватель отмечает наиболее активных студентов по своему усмотрению. -->

<!-- 4.*Устный экзамен*. Экзамен будет проходить в очной или дистантной форме. Каждый студент получит два вопроса (вопрос на знание теории плюс задача), на которые надо дать развернутые ответы. Экзаменатор вправе задавать дополнительные вопросы. -->



<!-- Каждый источник оценок вносит свой вклад в формирование итоговой оценки -->




<!-- | Источник оценки          	| Максимум баллов 	| Вес (%) 	| -->
<!-- |--------------------------	|:--------------:	|:-------:	| -->
<!-- | Тесты по содержанию лекций|       100      	|    3    	| -->
<!-- | Самостоятельная работа 1 	|       100      	|    1.5    	| -->
<!-- | Самостоятельная работа 2 	|       100      	|    1.5    	| -->
<!-- | Семинар 1                 	|        1       	|    3    	| -->
<!-- | Семинар 2                 	|        1       	|    3    	| -->
<!-- | Семинар 3                 	|        1       	|    3    	| -->
<!-- | Семинар 4                 	|        1       	|    3    	| -->
<!-- | Семинар 5                 	|        1       	|    3    	| -->
<!-- | Семинар 6                 	|        1       	|    3    	| -->
<!-- | Семинар 7                 	|        1       	|    3    	| -->
<!-- | Контрольная 1            	|       100      	|    1.5   	| -->
<!-- | Контрольная 2            	|       100      	|    1.5   	| -->
<!-- | Экзамен 1                	|        5       	|    35   	| -->
<!-- | Экзамен 2                	|        5       	|    35   	| -->


<!-- Итоговая оценка вычисляется по следующей формуле -->

<!-- $$ -->
<!-- Final Score = \sum({\frac{Real}{Max}}\times Weight) \% -->
<!-- $$ -->

<!-- где -->

<!-- -$Real$ --- Реально полученная оценка -->

<!-- -$Max$ --- Максимально возможная оценка -->

<!-- -$Weight$ --- Вес оценки (см. таблицу) -->


<!-- Оценки в зачетную ведомость выставляются в соответствии со следующей шкалой -->

<!-- | Балл                	| Сколько надо набрать   	| -->
<!-- |---------------------	|------------------------	| -->
<!-- | Отлично (A)             	| 90-100% от максимума 	| -->
<!-- | Хорошо (B)              	| 80 - 89% от  максимума	| -->
<!-- | Хорошо (C)   	| 70-79% от максимума 	| -->
<!-- | Удовлетворительно (D)	| 61 - 69% от максимума 	| -->
<!-- | Удовлетворительно (E)	| 51 - 60% от максимума 	| -->
<!-- | Неудовлетворительно (F)	| <50% от максимума 	| -->


<!-- <font color='blue'> -->
<!-- <font size=18px> -->


<!-- **Лучше работать весь семестр!** -->
<!-- </font> -->





<!-- Версия для биотехнологов -->

## Расписание и контакты

Лекции: с 13 февраля в **дистанционном режиме**. Лекции будут проходить в системе ZOOM, но администрирование курса будет проводиться с применением системы MS Teams.

О расписании семинаров объявим дополнительно

Лектор:

- Хайтов Вадим Михайлович - polydora[]rambler.ru

Инструктор семинаров:
- Ольга Валерьевна Князева    




Подготовка тестов и обслуживание сайта   
- Вадим Михайлович Хайтов   
- Ольга Валерьевна Князева    





## Структура курса, задания, дедлайны и оценки

Теоретическая часть курса состоит из двух частей.

**Часть 1** (первые 6 недель + 1 в резерве).

1.Лекции
2.Прохождение тестов и контрольные работы

**Часть  2** (2 недели)
3.Семинары



**Оценки**
Политика курса направлена на использование накопительной системы, в которой  дробные оценки накапливаются студентом за все время прохождения курса. Финальная оценка за курс (которая пойдет в ведомость) складывается из нескольких частей.


1. *Оценки за освоение материалов лекций*. Задача этих тестов - привлечение студентов к внимательной работе с лекционным материалом, стимуляция посещения лекций и создание основы для постепенного освоения материалов. Эти оценки производятся на основе тестов, которые будут размещены на платформе Ms Teams. За сутки до начала очередной лекции будет открыт тест по материалам **предыдущих** лекций. Тест будет закрыт одновременно со временем начала текущей лекции.


2.*Оценки за контрольные работы*. Всего будет две контрольные работы, которые будут проходить в формате online тестов. Каждый тест будет открыт для прохождения в определенный, согласованный с курсом, день. Студенты смогут его проходить в любом удобном для них месте, но только в течение 2 часов с момента начала тестирования.

3.*Оценки за семинары*. Посещение каждого семинара принесет один балл в накопление, но стоимость этих баалов достстаочно высока (см. таблицу ниже). По итогам семинаров студенты, активно работающие на занятиях, могут получить дополнительнo 0.5 балла. Преподаватель отмечает наиболее активных студентов по своему усмотрению.

4.*Устный экзамен*. Экзамен будет проходить в очной форме. Каждый студент получит два вопроса (вопрос на знание теории плюс задача), на которые надо дать развернутые ответы. Экзаменатор вправе задавать дополнительные вопросы.



Каждый источник оценок вносит свой вклад в формирование итоговой оценки


| Источник оценки          	| Максимум баллов 	| Вес (%) 	|
|--------------------------	|:--------------:	|:-------:	|
| Тесты по содержанию лекций|       100      	|    8    	|
| Семинар 1                 	|        1       	|    8   	|
| Семинар 2                 	|        1       	|    8    	|
| Контрольная 1            	|       100      	|    3   	|
| Контрольная 2            	|       100      	|    3   	|
| Экзамен 1                	|        5       	|    35   	|
| Экзамен 2                	|        5       	|    35   	|


Итоговая оценка вычисляется по следующей формуле

$$
Final Score = \sum({\frac{Real}{Max}}\times Weight) \%
$$

где

-$Real$ --- Реально полученная оценка

-$Max$ --- Максимально возможная оценка

-$Weight$ --- Вес оценки (см. таблицу)


Оценки зачетную ведомость выставляются в соответствии со следующей шкалой

| Балл                	| Сколько надо набрать   	|
|---------------------	|------------------------	|
| Отлично (A)             	| 90-100% от максимума 	|
| Хорошо (B)              	| 80 - 89% от  максимума	|
| Хорошо (C)   	| 70-79% от максимума 	|
| Удовлетворительно (D)	| 61 - 69% от максимума 	|
| Удовлетворительно (E)	| 51 - 60% от максимума 	|
| Неудовлетворительно (F)	| <50% от максимума 	|





<font color='blue'>
<font size=14px>


**Лучше работать весь семестр!**
</font>



