---
title: Презентации к лекциям
---

Презентации будут открываться по мере чтения лекций.

**Внимание! Важно!**  Не рекомендуется использовать презентации (и особенно видеозаписи), **которые скачали ваши предшественники**, проходя этот курс в прошлые годы. Все материалы каждый год перерабатываются, иногда коренным образом. Материалы по некоторым темам могут быть существенно дополнены и расширены. Особенно обращаем внимание на то, что содержание тестов по лекциям тоже меняется год от года. 


<!-- Версия для биологов -->

## Введение

- [Правила игры](Presentations/Lecture Introduction.pdf)

## Лекция 1.

- [Предмет экологии](Presentations//Lecture 1 Предмет экологии.pdf)

## Лекция 2.

- [Аутэкология](Presentations/Lecture 2 Аутэкология .pdf)

+ [**Тест по лекциям 1 и 2** дата окончания **13 сентября** (23:59)](https://forms.gle/R3wFo1wphqEoqh2H9) Дедлайн для данного теста **13.09.2025 в 23:59**. Работы, сданные после этого времени, **оцениваться не будут**.

Если вдруг, вы обнаружили, что вас нет в списке, то срочно пишите об этом в чате нашего ТГ-канала или в личном письме. 



## Лекция 3.

- [Демэкология](Presentations//Lecture 3 Популяция и ее структура.pdf)

+ [**Тест по теме "Популяционные группировки и их струкутра"** дата окончания **20 сентября** (23:59)](https://docs.google.com/forms/d/e/1FAIpQLSf8mYPyo77Pl64xWXDBSBBVJyIRnP8bjhfXc1pS48M0k1tXWg/viewform?usp=header)


<!-- ## Лекция 4. -->

<!-- - [Динамика популяции](Presentations//Lecture 4 Динамика популяции.pdf) -->


<!-- ## Лекция 5. -->

<!-- - [Взаимоотношения организмов (часть 1)](Presentations//Lecture 5 Симфизиология.pdf) -->


<!-- ## Лекция 6. -->

<!-- - [Взаимоотношения организмов (часть 2)](Presentations//Lecture 6 Классификация отношений.pdf) -->

<!-- ## Лекция 7. -->

<!-- - [Конкурентные отношения](Presentations//Lecture 7 Конкуренция.pdf) -->


<!-- ## Лекция 8. -->

<!-- - [Трофические связи](Presentations//Lecture 8 Трофические связи.pdf) -->



<!-- ## Лекция 9. -->

<!-- - [Симбиозы](Presentations//Lecture 9 Симбиозы.pdf) -->



<!-- ## Лекция 10. -->

<!-- - [Структура сообщества](Presentations//Lecture 10 Структура сообщества.pdf) -->


<!-- ## Лекция 11 и 12. -->

<!-- - [Экосистемы и сукцессии](Presentations//Lecture 11 Экосистема19.pdf) -->


<!-- - [Экосистемы хорологические единицы](Presentations//Lecture 13 Экосистемы хорологические единицы.pdf) -->


<!-- ## Презентация для семинара по теме "Температура и живые системы" -->

<!-- - [Температура](Presentations//Temperature living systems.pdf) -->


<!-- ## Презентация для семинара по теме "Экологические группировки гидробионтов" -->

<!-- - [Экологические группировки гидробионтов](Presentations//Экологические группы гидробионтов Презентация к семинару Чернова 2022.pdf) -->





<!-- Версия для биотехнологов -->

<!-- ## Введение -->

<!-- - [Правила игры](Presentations/Lecture Introduction (биотехнологи).pdf) -->

<!-- ## Лекция 1. Предмет экологии. -->

<!-- - [Предмет экологии](Presentations//Введение в ОТС. Суть экологии (биотехнологи).pdf) -->

<!-- ## Лекция 2. Аутоэкология. -->

<!-- - [Аутэкология](Presentations/Аутэкология (биотехнологи).pdf) -->



<!-- ## Лекция 3. Структура популяций. -->

<!-- - [Демэкология](Presentations//Популяции и их структура (биотехнологи).pdf) -->


<!-- ## Лекция 4. Динамика популяций. -->


<!-- - [Динамика популяции](Presentations//Динамика популяции (биотехнологи).pdf) -->


<!-- ## Лекции 5-6. Взаимоотношения организмов. -->

<!-- - [Взаимоотношения организмов. Часть 1.](Presentations//05_06_Взаимоотношения организмов (биотехнологи).pdf) -->

<!-- **Дополнительные материалы** -->

<!-- - [Классификация симфизиологических связей (по В. Н. Белемишеву)](Presentations//Lecture 5 Взаимоотношения часть 1.pdf) -->

<!-- - [Видео лекции про симфизиологические связи](https://drive.google.com/file/d/1qkhwZqhE-mmFarFXI5Vgyts-hiCnNuA4/view?usp=sharing) -->

<!-- - [Симбиозы](Presentations//Lecture 9 Симбиозы.pdf) -->
<!-- - [Симбиозы. Видео](https://drive.google.com/file/d/1ikI8bSG5vgUVa_CZpeQvYBeJ8jqUoKk0/view?usp=sharing) -->



<!-- ## Лекция 6. Трофические связи. -->

<!-- - [Трофические связи](Presentations//Трофические связи (биотехнологи).pdf) -->



<!-- ## Лекция 7. Конкурентные отношения и структура сообществ. -->

<!-- - [Конкуренция, экологические ниши и структура сообществ](Presentations//07_Конкуренция и структура сообществ (биотехнологи).pdf) -->


<!-- ## Лекции 8. Струкутра и динамика экосистем -->


<!-- - [Структура и динамика экоситсем](Presentations//08_Структура и динамика экосистем (биотехнологи).pdf) -->

<!-- - [Глобальные круговороты (дополнительные материалы)](Presentations//Биогеохимические циклы (биотехнологи).pdf) -->



<!-- ## Лекция 8. -->


<!-- - [Структура и динамика сообщества](Presentations//Структура и динамика сообществ (биотехнологи).pdf) -->



<!-- ## Лекция 7. -->

<!-- - [Конкурентные отношения](Presentations//Lecture 7 Конкуренция.pdf) -->


<!-- ## Лекция 8. -->

<!-- - [Трофические связи](Presentations//Lecture 8 Трофические отношения.pdf) -->



<!-- ## Лекция 9. -->

<!-- - [Симбиозы](Presentations//Lecture 9 Симбиозы.pdf) -->



<!-- ## Лекция 10. -->

<!-- - [Структура сообщества](Presentations//Lecture 10 Структура сообщества.pdf) -->


<!-- ## Лекция 11 и 12. -->

<!-- - [Экосистемы и сукцессии](Presentations//Lecture 11 Экосистема19.pdf) -->


<!-- - [Экосистемы хорологические единицы](Presentations//Lecture 13 Экосистемы хорологические единицы.pdf) -->


<!-- ## Презентация для семинара по теме "Температура и живые системы" -->

<!-- - [Температура](Presentations//Temperature living systems.pdf) -->






