---
title: "Календарь"
---

**Внимание!** В расписании могут быть изменения и уточнения.

Это рабочая версия расписания даты и последовательность занятий будут уточняться.



<!-- Версия для биологов -->


Расписание семинаров у каждой группы будет свое (см. страничку "Семинары")

## Суббота, 26 сентября (1 пара)
- В.М.Хайтов лекция "Вводные замечания к курсу, правила игры"
- В.М.Хайтов лекция "Предмет экологии"

## Среда, 7 октября (1 пара)
- В.М.Хайтов лекция "Аутэкология" (1-я часть)

- Открывается [тест с задачами по *самостоятельной работе №1*](https://docs.google.com/forms/d/e/1FAIpQLScpXWL0O9zTscld3i5bf5QSIVrbIKn8svn5rCzHn17JBcVytQ/viewform?usp=header), решение которых потребует освоения литературных источников.

## Четверг, 8 октября (5 пара)

- В.М.Хайтов лекция "Аутэкология" (2-я часть)




## Среда, 14 октября (1-я пара)

- В.М.Хайтов лекция "Демэкология (структура популяций организмов)"



## Четверг, 15 октября (5 пара)
- В.М.Хайтов лекция "Демэкология (Продолжение)"
- В.М.Хайтов лекция "Динамика популяций"



- **At!** *Согласуем дату и время контрольной работы №1* Темы: Аутэкология, Структура популяций, Динамика популяций.

**Внимание!** Точную дату и время проведения контрольной работы надо обсудить на лекции. НЕ ЗАБУДЬТЕ!!!


<!-- ## 21 сентября 2024  суббота (18:00 - 20:00) -->

<!-- **Контрольная работа № 1** (Темы: Аутэкология, Структура популяций, Динамика популяций.) -->



## Среда, 21 октября (1 пара)
- В.М.Хайтов лекция "Взаимоотношения организмов. Часть 1"

## Четверг, 22 октября (5 пара)

- В.М.Хайтов лекция "Взаимоотношения организмов. Часть 2"


## Среда, 28 октября

- В.М.Хайтов лекция "Конкурентные отношения"

## Четверг, 29 октября

НАЧАЛО СЕМИНАРОВ 


## Среда, 11 ноября (1 пара)

- В.М.Хайтов лекция "Трофические связи"

- Открывается тест по самостоятельной работе № 2.

- **At!** *Это срок закрытия теста по самостоятельной работе №1*



<!-- ## пятница, 19 сентября -->

<!-- - Контрольная работа №1 (с 20:00 до 22:00) -->


## Среда, 18 ноября (1 пара)

- В.М.Хайтов лекция "Симбиозы"



## Среда, 25 ноября (1 пара)

- В.М.Хайтов лекция "Структура сообщества"

- **Согласуем дату и время контрольной работы №2** Темы:Взаимоотношения организмов, Структура сообщества, Экосистемы, Многообразие жизненных циклов. Работа должна пройти после лекций М. Ю Тиходеевой (см. ниже)



##  Дата согласуется.

- М.Ю.Тиходеева лекция "Экосистемы" (1 часть)




##  Дата согласуется

- М.Ю.Тиходеева лекция "Экосистемы" (2 часть)



## 11 декабря


-**At!** *Это срок закрытия теста по самостоятельной работе №2*




<!-- ## С 27 октября (вторники). Семинары (16:50–18:30). -->

<!-- 5-я, пара **по вторникам**. Каждая группа идет по своему маршруту (см. страничку *"Семинары"*) -->


## Декабрь, по согласованию
- В. М. Хайтов. Консультация перед экзаменом "Трудные моменты курса"


<!-- ################################### -->
<!-- Версия для биотехнологов -->

<!-- ## 14 февраля -->
<!-- - Лекция "Предмет экологии" -->
<!-- - Лекция "Аутэкология" -->

<!-- ## 21 февраля -->

<!-- - Лекция "Структура популяций" -->
<!-- - Лекция "Динамика популяций" -->


<!-- - **Контрольная работа №1.** Темы: Введение в экологию, Аутэкология, Структура популяций, Динамика популяций. -->

<!-- **Внимание!** Точную дату и время проведения контрольной работы обсудим на лекции. -->


<!-- ## 7 марта -->

<!-- - Лекция "Многообразие взаимоотношений организмов. Часть 1" -->

<!-- - Лекция "Многообразие взаимоотношений организмов. Часть 1" -->



<!-- ## 14 марта -->

<!-- <!-- - Лекция "Симбиозы" --> -->

<!-- - Лекция "Конкурентнтые отношения и структура сообществ ". -->

<!-- - Лекция "Структура и динамика экосистем". -->


<!-- - **Контрольная работа №2.** Темы:Взаимоотношения организмов, Структура сообщества, Экосистемы. -->


<!-- ## 21 марта -->

<!-- - Семинар 1. -->

<!-- - Семинар 2. -->

<!-- ## Открытая дата -->

<!-- - Онлайн консультация: "Трудные моменты курса" (по согласованию с группой) -->







