---
title: Семинары
---
# Таблица расписания семинаров

**Если вы заметите какие-то накладки и нестыковки, то сразу пишите В. М. Хайтову**
В 2019 году семинары будут прохоить 



<!-- # **Первый семинар** 31.10.2018   -->

<!-- ## Группа №1 -->
<!-- На первой паре вы идете на кафедру геоботаники  и встречаетесь с Д. М. Мириным (Тема № 1) -->
<!-- Адрес Кафедры геоботаники: Средний проспект В.О., д.41/43.    -->


<!-- ## Группа №2 -->
<!-- На первой паре вы идете на кафедру Зоологии позвоночных (в лекционный зал) и встречаетесь с В. А. Крапивиным и А.Г.Гончар (Тема № 5) -->

<!-- Адрес Кафедры зоологии позвоночных: Главное здание, рядос с аудиторией 143 -->


<!-- ## Группа №3 -->
<!-- На четвертой паре вы идете на кафедру геоботаники и встречаетесь с Е. М. Копцевой (Тема № 2) -->
<!-- Адрес Кафедры геоботаники: Средний проспект В.О., д.41/43.    -->


<!-- ## Группа №4 -->
<!-- На четвертой паре вы идете на кафедру энтомологии и встречаетесь с С. И. Мельницким (Тема №4) -->
<!-- Адрес Кафедры энтомологии: В здании, где располагается Менделеевский научный центр (надо обогнуть кафедру Генетики).    -->




<!-- ## Группа №5 -->
<!-- На четвертой паре вы идете на кафедру прикладной экологии и встречаетесь с Д. В. Сафроновой и Е. Н. Черновой (Тема №3). -->

<!-- Адрес Кафедры прикладной экологии: 16-я линия, д.29, 1 этаж. -->

<!-- ## Группа №6 -->
<!-- На четвертой паре вы идете на кафедру генетики (аудитория Г15) и встречаетесь с Д. А. Кучеровым (Тема №6) -->

<!-- Адрес Кафедры генетики: Рядом с кафедрой ботаники. -->

<!-- <br> -->
<!-- <br> -->
<!-- <br> -->
<!-- <br> -->
<!-- <br> -->
<!-- <br> -->


<!-- **Если будут какие-то организационные вопросы, то связывайтесь с преподавателями или с В. М. Хайтовым** -->

<!-- <br> -->
<!-- <br> -->
<!-- <br> -->

<!-- # Оценки за семинары -->

<!-- ```{r, echo=FALSE} -->

<!-- library(knitr) -->
<!-- sem <- read.csv("data/Seminars_2018.csv", header = T) -->
<!-- topics <- c("Функциональная структура сообществ (взаимоотношения организмов)", -->
<!--             "Динамика экосистем: сукцессии и флуктуации", -->
<!--             "Приспособление водных организмов к среде обитания", -->
<!--             "Эволюционные экологические адаптации", -->
<!--             "Взаимоотношения симбионтов и хозяев", -->
<!--             "Температура и живые системы: эксперименты, модели, практическое значение") -->
<!-- schedul <- read.csv("data/schedul_2018.csv", header = T) -->

<!-- # library(reshape2) -->
<!-- # write.table(melt(schedul, id.vars = "Group"), "clipboard", sep = "\t", row.names = F)  -->

<!-- ``` -->


<!-- ## Первый первый семинар  -->

<!-- **Коллеги!**  -->

<!-- Вы большие молодцы! По отзывам преподавателей, первые семинары прошли успешно. Далее все будет по той же схеме: за неделю до семинара вы должны связаться с преподавателем (всем сразу не надо, от группы достаточно одного инициативного человека) и выяснить у него задание. К семинару надо готовиться! -->

<!-- Вот те, кто отличился на первом семинаре.     -->
<!-- Им будет добавлено по 3% к результатам самостоятельной работы или контрольным. -->

<!-- ```{r, echo=FALSE} -->
<!-- good <- sem[sem$Seminar_1 == 1 & !is.na(sem$Seminar_1), ] -->

<!-- result <- data.frame(Group = good$Group, Name = paste(good$Last_name, " ", good$First_name)) -->

<!-- kable(result, col.names = c("Группа", "Ф. И."), caption = "Активные участники семинара", align = c("c", "l")) -->

<!-- ``` -->




<!-- ### Задолженности по первому семинару  -->
<!-- Внимание, ниже приведены имена тех, кто должен связаться с В. М. Хайтовым или преподавателем соответствующего семинара для получения темы эссе. *Без этой отработки допуска к экзамену не будет*. Не тяните! -->


<!-- ```{r, echo=FALSE} -->
<!-- bad <- sem[sem$Seminar_1 == 0 & !is.na(sem$Seminar_1), ] -->
<!-- ``` -->

<!-- Для начала, вот имена тех людей, принадлежность которых к той или иной группе неизвестна, их не было на семинаре, но они отметились на Stepik.  Отзовитесь, пожалуйста!  -->

<!-- ```{r, echo=FALSE} -->
<!-- kable(paste(bad$Last_name, " ", bad$First_name) [is.na(bad$Group)], col.names = "Ф. И.") -->
<!-- ``` -->


<!-- А вот те, у кого появилась задолженность. Если здесь что-то не так (например, вы были на семинаре), то срочно пишите, я свяжусь с преподавателями и проверю. -->


<!-- ```{r, echo=FALSE} -->
<!-- bad2 <- bad[!is.na(bad$Group),] -->
<!-- result_bad <- data.frame(bad2$Group, paste(bad2$Last_name, " ", bad2$First_name), Topic = topics[bad2$Group]) -->

<!-- kable(result_bad, col.names = c("Группа", "Ф. И.", "Тема"), caption = "Задолженности", align = c("c", "l", "r") ) -->
<!-- ``` -->



<!-- ## Второй семинар  -->

<!-- Вот отчет преподавателей о втором семинаре. Это имена тех, кто отличился, им будет добавлено по 3% к результатам самостоятельной работы или контрольным. -->

<!-- ```{r, echo=FALSE} -->
<!-- good <- sem[sem$Seminar_2 == 1 & !is.na(sem$Seminar_2), ] -->

<!-- result <- data.frame(Group = good$Group, Name = paste(good$Last_name, " ", good$First_name)) -->

<!-- kable(result, col.names = c("Группа", "Ф. И."), caption = "Активные участники семинара", align = c("c", "l")) -->

<!-- ``` -->



<!-- Несколько снизилась интенсивность работы в нескольких группах. Постарайтесь ее нарастить на оставшихся четырех семинарах. -->

<!-- ```{r, echo=FALSE} -->
<!-- library(reshape2) -->
<!-- library(ggplot2) -->

<!-- dynamics <- melt(sem, id.vars = c("Group","Last_name", "First_name")) -->
<!-- dynamics <- dynamics[!is.na(dynamics$value) & !is.na(dynamics$Group), ] -->

<!-- ggplot(dynamics, aes(x = variable, y = value)) + stat_summary(fun.y = sum, geom = "bar", fill = "blue", color = "black") + facet_wrap(~ Group, ncol = 2) + labs(x = "Семинары", y = "Количество активных участников") + theme_bw() -->



<!-- ``` -->




<!-- ### Задолженности по второму семинару  -->
<!-- Внимание, ниже приведены имена тех, кто должен связаться с В. М. Хайтовым  для получения темы эссе. *Без этой отработки допуска к экзамену не будет*. Не тяните! -->

<!-- Надеюсь, что в ближайшее время темы эссе будут окончательно сформулированы.  -->


<!-- ```{r, echo=FALSE} -->
<!-- bad <- sem[sem$Seminar_2 == 0 & !is.na(sem$Seminar_2), ] -->
<!-- ``` -->

<!-- Еще раз имена тех людей, принадлежность которых к той или иной группе неизвестна, их не было на семинаре, но они отметились на Stepik.  Отзовитесь, пожалуйста!  -->

<!-- Возможно, это люди, которые проходят тесты, но пришли откуда-то извне. -->

<!-- ```{r, echo=FALSE} -->
<!-- kable(paste(bad$Last_name, " ", bad$First_name) [is.na(bad$Group)], col.names = "Ф. И.") -->
<!-- ``` -->


<!-- А вот те, у кого появилась задолженность. Если здесь что-то не так (например, вы были на семинаре), то срочно пишите, я свяжусь с преподавателями и проверю. -->


<!-- ```{r, echo=FALSE} -->
<!-- bad2 <- bad[!is.na(bad$Group),] -->
<!-- result_bad <- data.frame(bad2$Group, paste(bad2$Last_name, " ", bad2$First_name), Topic = topics[schedul$Seminar_2[bad2$Group]]) -->

<!-- kable(result_bad, col.names = c("Группа", "Ф. И.", "Тема"), caption = "Задолженности", align = c("c", "l", "r") ) -->
<!-- ``` -->




<!-- ## Третий семинар  -->

<!-- Вот отчет преподавателей о третьем семинаре. Очередная серия отличившихся. -->

<!-- ```{r, echo=FALSE} -->
<!-- good <- sem[sem$Seminar_3 == 1 & !is.na(sem$Seminar_3), ] -->

<!-- result <- data.frame(Group = good$Group, Name = paste(good$Last_name, " ", good$First_name)) -->

<!-- kable(result, col.names = c("Группа", "Ф. И."), caption = "Активные участники семинара", align = c("c", "l")) -->

<!-- ``` -->


<!-- Молодцы! Количество активных участников вновь выросло почти во всех группах. Или это очередные "популяционные циклы"? -->


<!-- ```{r, echo=FALSE} -->
<!-- library(reshape2) -->
<!-- library(ggplot2) -->

<!-- dynamics <- melt(sem, id.vars = c("Group","Last_name", "First_name")) -->
<!-- dynamics <- dynamics[!is.na(dynamics$value) & !is.na(dynamics$Group), ] -->

<!-- ggplot(dynamics, aes(x = variable, y = value)) + stat_summary(fun.y = sum, geom = "bar", fill = "blue", color = "black") + facet_wrap(~ Group, ncol = 2) + labs(x = "Семинары", y = "Количество активных участников") + theme_bw() -->



<!-- ``` -->




<!-- ### Задолженности по тертьему семинару  -->

<!-- ```{r, echo=FALSE} -->
<!-- bad <- sem[sem$Seminar_3 == 0 & !is.na(sem$Seminar_3), ] -->
<!-- ``` -->


<!-- Опять же, если здесь что-то не так (например, вы были на семинаре), то срочно пишите, я свяжусь с преподавателями и проверю. -->


<!-- ```{r, echo=FALSE} -->
<!-- bad2 <- bad[!is.na(bad$Group),] -->
<!-- result_bad <- data.frame(bad2$Group, paste(bad2$Last_name, " ", bad2$First_name), Topic = topics[schedul$Seminar_3[bad2$Group]]) -->

<!-- kable(result_bad, col.names = c("Группа", "Ф. И.", "Тема"), caption = "Задолженности", align = c("c", "l", "r") ) -->
<!-- ``` -->





<!-- ## Четвертый семинар  -->

<!-- Вот отчет преподавателей о четвертом семинаре. Очередная серия отличившихся. -->

<!-- ```{r, echo=FALSE} -->
<!-- good <- sem[sem$Seminar_4 == 1 & !is.na(sem$Seminar_4), ] -->

<!-- result <- data.frame(Group = good$Group, Name = paste(good$Last_name, " ", good$First_name)) -->

<!-- kable(result, col.names = c("Группа", "Ф. И."), caption = "Активные участники семинара", align = c("c", "l")) -->

<!-- ``` -->




<!-- ```{r, echo=FALSE} -->
<!-- library(reshape2) -->
<!-- library(ggplot2) -->

<!-- dynamics <- melt(sem, id.vars = c("Group","Last_name", "First_name")) -->
<!-- dynamics <- dynamics[!is.na(dynamics$value) & !is.na(dynamics$Group), ] -->

<!-- ggplot(dynamics, aes(x = variable, y = value)) + stat_summary(fun.y = sum, geom = "bar", fill = "blue", color = "black") + facet_wrap(~ Group, ncol = 2) + labs(x = "Семинары", y = "Количество активных участников") + theme_bw() -->



<!-- ``` -->




<!-- ### Задолженности по Четвертому семинару  -->

<!-- ```{r, echo=FALSE} -->
<!-- bad <- sem[sem$Seminar_4 == 0 & !is.na(sem$Seminar_4), ] -->
<!-- ``` -->


<!-- Опять же, если здесь что-то не так (например, вы были на семинаре), то срочно пишите, я свяжусь с преподавателями и проверю. -->


<!-- ```{r, echo=FALSE} -->
<!-- bad2 <- bad[!is.na(bad$Group),] -->
<!-- result_bad <- data.frame(bad2$Group, paste(bad2$Last_name, " ", bad2$First_name), Topic = topics[schedul$Seminar_4[bad2$Group]]) -->

<!-- kable(result_bad, col.names = c("Группа", "Ф. И.", "Тема"), caption = "Задолженности", align = c("c", "l", "r") ) -->
<!-- ``` -->






<!-- ## Пятый семинар  -->

<!-- Вот отчет преподавателей о пятом семинаре. Очередная серия отличившихся. -->

<!-- ```{r, echo=FALSE} -->
<!-- good <- sem[sem$Seminar_5 == 1 & !is.na(sem$Seminar_5), ] -->

<!-- result <- data.frame(Group = good$Group, Name = paste(good$Last_name, " ", good$First_name)) -->

<!-- kable(result, col.names = c("Группа", "Ф. И."), caption = "Активные участники семинара", align = c("c", "l")) -->

<!-- ``` -->




<!-- ```{r, echo=FALSE} -->
<!-- library(reshape2) -->
<!-- library(ggplot2) -->

<!-- dynamics <- melt(sem, id.vars = c("Group","Last_name", "First_name")) -->
<!-- dynamics <- dynamics[!is.na(dynamics$value) & !is.na(dynamics$Group), ] -->

<!-- ggplot(dynamics, aes(x = variable, y = value)) + stat_summary(fun.y = sum, geom = "bar", fill = "blue", color = "black") + facet_wrap(~ Group, ncol = 2) + labs(x = "Семинары", y = "Количество активных участников") + theme_bw() -->



<!-- ``` -->




<!-- ### Задолженности по Пятому семинару  -->

<!-- ```{r, echo=FALSE} -->
<!-- bad <- sem[sem$Seminar_5 == 0 & !is.na(sem$Seminar_5), ] -->
<!-- ``` -->


<!-- Опять же, если здесь что-то не так (например, вы были на семинаре), то срочно пишите, я свяжусь с преподавателями и проверю. -->


<!-- ```{r, echo=FALSE} -->
<!-- bad2 <- bad[!is.na(bad$Group),] -->
<!-- result_bad <- data.frame(bad2$Group, paste(bad2$Last_name, " ", bad2$First_name), Topic = topics[schedul$Seminar_5[bad2$Group]]) -->

<!-- kable(result_bad, col.names = c("Группа", "Ф. И.", "Тема"), caption = "Задолженности", align = c("c", "l", "r") ) -->
<!-- ``` -->






<!-- ## Шестой семинар  -->


<!-- ```{r, echo=FALSE} -->
<!-- good <- sem[sem$Seminar_6 == 1 & !is.na(sem$Seminar_6), ] -->

<!-- result <- data.frame(Group = good$Group, Name = paste(good$Last_name, " ", good$First_name)) -->

<!-- kable(result, col.names = c("Группа", "Ф. И."), caption = "Активные участники семинара", align = c("c", "l")) -->

<!-- ``` -->




<!-- ```{r, echo=FALSE} -->
<!-- library(reshape2) -->
<!-- library(ggplot2) -->

<!-- dynamics <- melt(sem, id.vars = c("Group","Last_name", "First_name")) -->
<!-- dynamics <- dynamics[!is.na(dynamics$value) & !is.na(dynamics$Group), ] -->

<!-- <!-- ggplot(dynamics, aes(x = variable, y = value)) + stat_summary(fun.y = sum, geom = "bar", fill = "blue", color = "black") + facet_wrap(~ Group, ncol = 2) + labs(x = "Семинары", y = "Количество активных участников") + theme_bw() --> -->



<!-- ``` -->




<!-- ### Задолженности по Шестому семинару  -->

<!-- ```{r, echo=FALSE} -->
<!-- bad <- sem[sem$Seminar_6 == 0 & !is.na(sem$Seminar_6), ] -->
<!-- ``` -->


<!-- Опять же, если здесь что-то не так (например, вы были на семинаре), то срочно пишите, я свяжусь с преподавателями и проверю. -->


<!-- ```{r, echo=FALSE} -->
<!-- bad2 <- bad[!is.na(bad$Group),] -->
<!-- result_bad <- data.frame(bad2$Group, paste(bad2$Last_name, " ", bad2$First_name), Topic = topics[schedul$Seminar_6[bad2$Group]]) -->

<!-- kable(result_bad, col.names = c("Группа", "Ф. И.", "Тема"), caption = "Задолженности", align = c("c", "l", "r") ) -->
<!-- ``` -->









<!-- # **Темы эссе для отработки пропущенных семинаров** -->
<!-- <br> -->
<!-- <br> -->

<!-- _______________________________________________________ -->

<!-- **ВНИМАНИЕ! Срок окончательной сдачи эссе --- 19 декабря (это одна неделя после окончания последнего семинара). После этой даты начинаются проблемы! Те, у кого уже известно, что есть долг, не тяните, эссе можно присылать уже сейчас.** -->

<!-- _______________________________________________________ -->

<!-- <br> -->
<!-- <br> -->
<!-- <br> -->

<!-- Вам предстоит написать текст объемом до 2 страниц формата A4. Рисунки в объем не входят.  Эссе пишется в вольной форме, но при этом тема должна быть раскрыта. Представьте, что вам необходимо прочитать доклад по заданной теме, эссе и будет текстом этого доклада.   -->

<!-- Предупреждаем, что приемы типа ctrl-C ctrl-V и прочее жульничество будут отлавливаться и за них будет ставиться понижающий коэффициент (-3%). -->

<!-- Эссе должно содержать фамилию и имя автора. В конце текста необходимо привести список использованных источников. Источники могут быть любые, но ссылка на них обязательна. -->

<!-- Сохраните ваши готовые работы в формате **pdf** и присылайте их на электронный адрес В. М. Хайтова (обязательно **с указанием темы «эссе по экологии»**, иначе письмо может уйти в спам и не вернуться).   -->


<!-- ### **Информация для должников** -->
<!-- Как выяснилось, запрет на доступ к экзамену, опция недоступная. Поэтому санкция для должников, которые не сдадут эссе вовремя, будет в форме дополнительного вопроса (билета) на экзамене за каждый долг. Так что если не хотите рисковать, то пишите тексты. -->



<!-- ## Темы эссе для должников по семиарам № 1 и № 2 -->


<!-- ```{r, echo=FALSE, warning=FALSE, message=FALSE} -->
<!-- sem <- read.csv("data/Seminars_2018.csv", header = T) -->
<!-- topics <- c("Функциональная структура сообществ (взаимоотношения организмов)", -->
<!--             "Динамика экосистем: сукцессии и флуктуации", -->
<!--             "Приспособление водных организмов к среде обитания", -->
<!--             "Эволюционные экологические адаптации", -->
<!--             "Взаимоотношения симбионтов и хозяев", -->
<!--             "Температура и живые системы: эксперименты, модели, практическое значение") -->
<!-- schedul <- read.csv("data/schedul_2018.csv", header = T) -->

<!-- esse <- read.csv("data/Esse_topics_2018.csv") -->

<!-- sem <- sem[,c(1:5)] -->

<!-- library(reshape2) -->

<!-- sem_long <- melt(sem, id.vars = c("Group","Last_name", "First_name")) -->
<!-- sem_long <- sem_long[!is.na(sem_long$Group), ] -->
<!-- dolg <- sem_long[sem_long$value == 0, ] -->
<!-- dolg <- dolg[!is.na(dolg$Group), ] -->
<!-- topic_long <- melt(schedul, id.vars = "Group") -->
<!-- dolg <- merge(dolg, topic_long, by = c("Group", "variable")) -->

<!-- names(dolg)[6] <- "Topic" -->
<!-- dolg$esse <- NA -->


<!-- for(i in unique(dolg$Topic)) { -->
<!--   dolg$esse[dolg$Topic == i] <- paste(as.character(esse$Task[esse$Topic == i])) -->
<!-- } -->



<!-- dolg_report <- data.frame(Name = paste(dolg$Last_name, ' ', dolg$First_name), Group = dolg$Group, Seminar = as.numeric(dolg$variable) -->
<!-- ,  Topic = dolg$Topic, Esse = paste(dolg$esse))  -->

<!-- kable(dolg_report, col.names = c("Ф. И.","Группа", "Cеминар",  "Номер темы", "Тема эссе"), align = "lcccl")  -->

<!-- # write.csv(dolg_report, "data/Seminar_dolg_2018_5.csv", sep = ",", row.names = FALSE)   -->

<!-- ``` -->


<!-- ## Темы эссе для должников по семиар № 3 -->


<!-- ```{r, echo=FALSE, warning=FALSE, message=FALSE} -->
<!-- sem <- read.csv("data/Seminars_2018.csv", header = T) -->
<!-- topics <- c("Функциональная структура сообществ (взаимоотношения организмов)", -->
<!--             "Динамика экосистем: сукцессии и флуктуации", -->
<!--             "Приспособление водных организмов к среде обитания", -->
<!--             "Эволюционные экологические адаптации", -->
<!--             "Взаимоотношения симбионтов и хозяев", -->
<!--             "Температура и живые системы: эксперименты, модели, практическое значение") -->
<!-- schedul <- read.csv("data/schedul_2018.csv", header = T) -->

<!-- esse <- read.csv("data/Esse_topics_2018.csv") -->

<!-- sem <- sem[ ,c(1:3, 6)] -->

<!-- library(reshape2) -->

<!-- sem_long <- melt(sem, id.vars = c("Group","Last_name", "First_name")) -->
<!-- sem_long <- sem_long[!is.na(sem_long$Group), ] -->
<!-- dolg <- sem_long[sem_long$value == 0, ] -->
<!-- dolg <- dolg[!is.na(dolg$Group), ] -->
<!-- topic_long <- melt(schedul, id.vars = "Group") -->
<!-- dolg <- merge(dolg, topic_long, by = c("Group", "variable")) -->

<!-- names(dolg)[6] <- "Topic" -->
<!-- dolg$esse <- NA -->


<!-- for(i in unique(dolg$Topic)) { -->
<!--   dolg$esse[dolg$Topic == i] <- paste(as.character(esse$Task[esse$Topic == i])) -->
<!-- } -->



<!-- dolg_report <- data.frame(Name = paste(dolg$Last_name, ' ', dolg$First_name), Group = dolg$Group, Topic = dolg$Topic, Esse = paste(dolg$esse))  -->

<!-- kable(dolg_report, col.names = c("Ф. И.","Группа",  "Номер темы", "Тема эссе"), align = "lccl")  -->

<!-- # write.csv(dolg_report, "data/Seminar_dolg_2018_2.csv", sep = ",", row.names = FALSE)   -->

<!-- ``` -->


<!-- ## Темы эссе для должников по семиару № 4 -->


<!-- ```{r, echo=FALSE, warning=FALSE, message=FALSE} -->
<!-- sem <- read.csv("data/Seminars_2018.csv", header = T) -->
<!-- topics <- c("Функциональная структура сообществ (взаимоотношения организмов)", -->
<!--             "Динамика экосистем: сукцессии и флуктуации", -->
<!--             "Приспособление водных организмов к среде обитания", -->
<!--             "Эволюционные экологические адаптации", -->
<!--             "Взаимоотношения симбионтов и хозяев", -->
<!--             "Температура и живые системы: эксперименты, модели, практическое значение") -->
<!-- schedul <- read.csv("data/schedul_2018.csv", header = T) -->

<!-- esse <- read.csv("data/Esse_topics_2018.csv") -->

<!-- sem <- sem[ ,c(1:3, 7)] ## Выбор номера семинара -->

<!-- library(reshape2) -->

<!-- sem_long <- melt(sem, id.vars = c("Group","Last_name", "First_name")) -->
<!-- sem_long <- sem_long[!is.na(sem_long$Group), ] -->
<!-- dolg <- sem_long[sem_long$value == 0, ] -->
<!-- dolg <- dolg[!is.na(dolg$Group), ] -->
<!-- topic_long <- melt(schedul, id.vars = "Group") -->
<!-- dolg <- merge(dolg, topic_long, by = c("Group", "variable")) -->

<!-- names(dolg)[6] <- "Topic" -->
<!-- dolg$esse <- NA -->


<!-- for(i in unique(dolg$Topic)) { -->
<!--   dolg$esse[dolg$Topic == i] <- paste(as.character(esse$Task[esse$Topic == i])) -->
<!-- } -->



<!-- dolg_report <- data.frame(Name = paste(dolg$Last_name, ' ', dolg$First_name), Group = dolg$Group, Topic = dolg$Topic, Esse = paste(dolg$esse))  -->

<!-- kable(dolg_report, col.names = c("Ф. И.","Группа",  "Номер темы", "Тема эссе"), align = "lccl")  -->

<!-- # write.csv(dolg_report, "data/Seminar_dolg_2018_4.csv", sep = ",", row.names = FALSE)   -->

<!-- ``` -->




<!-- ## Темы эссе для должников по семиару № 5 -->


<!-- ```{r, echo=FALSE, warning=FALSE, message=FALSE} -->
<!-- sem <- read.csv("data/Seminars_2018.csv", header = T) -->
<!-- topics <- c("Функциональная структура сообществ (взаимоотношения организмов)", -->
<!--             "Динамика экосистем: сукцессии и флуктуации", -->
<!--             "Приспособление водных организмов к среде обитания", -->
<!--             "Эволюционные экологические адаптации", -->
<!--             "Взаимоотношения симбионтов и хозяев", -->
<!--             "Температура и живые системы: эксперименты, модели, практическое значение") -->
<!-- schedul <- read.csv("data/schedul_2018.csv", header = T) -->

<!-- esse <- read.csv("data/Esse_topics_2018.csv") -->

<!-- sem <- sem[ ,c(1:3, 8)] ## Выбор номера семинара -->

<!-- library(reshape2) -->

<!-- sem_long <- melt(sem, id.vars = c("Group","Last_name", "First_name")) -->
<!-- sem_long <- sem_long[!is.na(sem_long$Group), ] -->
<!-- dolg <- sem_long[sem_long$value == 0, ] -->
<!-- dolg <- dolg[!is.na(dolg$Group), ] -->
<!-- topic_long <- melt(schedul, id.vars = "Group") -->
<!-- dolg <- merge(dolg, topic_long, by = c("Group", "variable")) -->

<!-- names(dolg)[6] <- "Topic" -->
<!-- dolg$esse <- NA -->


<!-- for(i in unique(dolg$Topic)) { -->
<!--   dolg$esse[dolg$Topic == i] <- paste(as.character(esse$Task[esse$Topic == i])) -->
<!-- } -->



<!-- dolg_report <- data.frame(Name = paste(dolg$Last_name, ' ', dolg$First_name), Group = dolg$Group, Topic = dolg$Topic, Esse = paste(dolg$esse))  -->

<!-- kable(dolg_report, col.names = c("Ф. И.","Группа",  "Номер темы", "Тема эссе"), align = "lccl")  -->

<!-- # write.csv(dolg_report, "data/Seminar_dolg_2018_5.csv", sep = ",", row.names = FALSE)   -->

<!-- ``` -->






<!-- ## Темы эссе для должников по семиару № 6 -->


<!-- ```{r, echo=FALSE, warning=FALSE, message=FALSE} -->
<!-- sem <- read.csv("data/Seminars_2018.csv", header = T) -->
<!-- topics <- c("Функциональная структура сообществ (взаимоотношения организмов)", -->
<!--             "Динамика экосистем: сукцессии и флуктуации", -->
<!--             "Приспособление водных организмов к среде обитания", -->
<!--             "Эволюционные экологические адаптации", -->
<!--             "Взаимоотношения симбионтов и хозяев", -->
<!--             "Температура и живые системы: эксперименты, модели, практическое значение") -->
<!-- schedul <- read.csv("data/schedul_2018.csv", header = T) -->

<!-- esse <- read.csv("data/Esse_topics_2018.csv") -->

<!-- sem <- sem[ ,c(1:3, 9)] ## Выбор номера семинара -->

<!-- library(reshape2) -->

<!-- sem_long <- melt(sem, id.vars = c("Group","Last_name", "First_name")) -->
<!-- sem_long <- sem_long[!is.na(sem_long$Group), ] -->
<!-- dolg <- sem_long[sem_long$value == 0, ] -->
<!-- dolg <- dolg[!is.na(dolg$Group), ] -->
<!-- topic_long <- melt(schedul, id.vars = "Group") -->
<!-- dolg <- merge(dolg, topic_long, by = c("Group", "variable")) -->

<!-- names(dolg)[6] <- "Topic" -->
<!-- dolg$esse <- NA -->


<!-- for(i in unique(dolg$Topic)) { -->
<!--   dolg$esse[dolg$Topic == i] <- paste(as.character(esse$Task[esse$Topic == i])) -->
<!-- } -->



<!-- dolg_report <- data.frame(Name = paste(dolg$Last_name, ' ', dolg$First_name), Group = dolg$Group, Topic = dolg$Topic, Esse = paste(dolg$esse))  -->

<!-- kable(dolg_report, col.names = c("Ф. И.","Группа",  "Номер темы", "Тема эссе"), align = "lccl")  -->

<!-- # write.csv(dolg_report, "data/Seminar_dolg_2018_6.csv", sep = ",", row.names = FALSE)   -->

<!-- ``` -->

<!-- <br> -->
<!-- <br> -->

<!-- _______________________________________________________ -->

<!-- **ВНИМАНИЕ! Срок окончательной сдачи эссе --- 19 декабря (это одна неделя после окончания последнего семинара). После этой даты начинаются проблемы! Те, у кого уже известно, что есть долг, не тяните, эссе можно присылать уже сейчас.** -->

<!-- _______________________________________________________ -->

<!-- <br> -->
<!-- <br> -->
<!-- <br> -->

<!-- # Общий список тем эссе для отработки семинаров -->

<!-- ```{r, echo=FALSE} -->
<!-- esse_total <- read.csv("data/Seminar_dolg_total_2018.csv", header = TRUE) -->

<!-- esse_total_print <- esse_total[order(esse_total$Status, esse_total$Name, decreasing = TRUE), ] -->
<!-- kable(esse_total_print) -->

<!-- ``` -->






<!-- # Общий итог по сминарам  -->

<!-- ```{r, echo=FALSE} -->

<!-- sem_fin <- read.csv("data/Seminars_2018_final.csv", header = TRUE) -->
<!-- sem_fin_2 <- sem_fin -->

<!-- sem_fin_2$Seminar_1[is.na(sem_fin_2$Seminar_1)] <- "зачет" -->
<!-- sem_fin_2$Seminar_2[is.na(sem_fin_2$Seminar_2)] <- "зачет" -->
<!-- sem_fin_2$Seminar_3[is.na(sem_fin_2$Seminar_3)] <- "зачет" -->
<!-- sem_fin_2$Seminar_4[is.na(sem_fin_2$Seminar_4)] <- "зачет" -->
<!-- sem_fin_2$Seminar_5[is.na(sem_fin_2$Seminar_5)] <- "зачет" -->
<!-- sem_fin_2$Seminar_6[is.na(sem_fin_2$Seminar_6)] <- "зачет" -->

<!-- sem_fin_2$Seminar_1[sem_fin_2$Seminar_1 == "1"] <- "Отл." -->
<!-- sem_fin_2$Seminar_2[sem_fin_2$Seminar_2 == "1"] <- "Отл." -->
<!-- sem_fin_2$Seminar_3[sem_fin_2$Seminar_3 == "1"] <- "Отл." -->
<!-- sem_fin_2$Seminar_4[sem_fin_2$Seminar_4 == "1"] <- "Отл." -->
<!-- sem_fin_2$Seminar_5[sem_fin_2$Seminar_5 == "1"] <- "Отл." -->
<!-- sem_fin_2$Seminar_6[sem_fin_2$Seminar_6 == "1"] <- "Отл." -->


<!-- sem_fin_2$Seminar_1[sem_fin_2$Seminar_1 == "0"] <- "Долг" -->
<!-- sem_fin_2$Seminar_2[sem_fin_2$Seminar_2 == "0"] <- "Долг" -->
<!-- sem_fin_2$Seminar_3[sem_fin_2$Seminar_3 == "0"] <- "Долг" -->
<!-- sem_fin_2$Seminar_4[sem_fin_2$Seminar_4 == "0"] <- "Долг" -->
<!-- sem_fin_2$Seminar_5[sem_fin_2$Seminar_5 == "0"] <- "Долг" -->
<!-- sem_fin_2$Seminar_6[sem_fin_2$Seminar_6 == "0"] <- "Долг" -->


<!-- sem_fin_2$Seminar_1[sem_fin_2$Seminar_1 == "-1"] <- "Неуд." -->
<!-- sem_fin_2$Seminar_2[sem_fin_2$Seminar_2 == "-1"] <- "Неуд." -->
<!-- sem_fin_2$Seminar_3[sem_fin_2$Seminar_3 == "-1"] <- "Неуд." -->
<!-- sem_fin_2$Seminar_4[sem_fin_2$Seminar_4 == "-1"] <- "Неуд." -->
<!-- sem_fin_2$Seminar_5[sem_fin_2$Seminar_5 == "-1"] <- "Неуд." -->
<!-- sem_fin_2$Seminar_6[sem_fin_2$Seminar_6 == "-1"] <- "Неуд." -->

<!-- library(knitr) -->

<!-- kable(sem_fin_2) -->

<!-- ``` -->


<!-- <br> -->
<!-- <br> -->
<!-- <br> -->

<!-- # Долги по семинарам -->

<!-- Коллеги, у кого образовались долги, изучите, пожалуйста,  таблицу, приведеную ниже. Там указаны темы, по которым у вас образовалась задолженность. Просмотрите соответствующие темы семинаров (ниже). На экзамене вам будут заданы вопросы по теме пропущенного семинара.  -->

<!-- <br> -->

<!-- ```{r} -->
<!-- dolg <- read.csv("data/dolg_seminar_for_exam.csv") -->
<!-- kable(dolg, col.names = c("Группа", "Номер семинара", "Ф. И.", "Темы, по которым есть долг"), align = "lclc") -->
<!-- ``` -->

<!-- <br> -->
<!-- <br> -->

<!-- _______________________________________________________________ -->




# **Содержание семинаров и задания** 

## Тема №1.  Функциональная структура сообществ (взаимоотношения организмов)

**Денис Моисеевич Мирин** (*каф. Геоботаники*) mirin_denis[]mail.ru

*Участники семинара идут на кафедру геоботаники  и встречаются с Д. М. Мириным* 

- Адрес Кафедры геоботаники: Средний проспект В.О., д.41/43.


*Будут затронуты следующие вопросы*  

1.Разнообразие типов взаимоотношений организмов. Биологические единицы, вступающие в системообразующие взаимоотношения. Индивидуальные и коллективные взаимоотношения. Прямые и опосредованные взаимоотношения. Взаимоотношения внутри одного трофического уровня и между организмами разных трофических уровней.    

2.Взаимодействия с меняющимся эффектом в зависимости силы воздействия. Приспособительные взаимоотношения организмов. Эдификаторы и ассектаторы. Ключевые виды экосистемы.     

3.Конкуренция, ее механизмы, необходимые условия, зависимость эффекта от внешних факторов и начальных условий. Способы выявления эффектов конкуренции. Конкуренция в разных типах сообществ.     

4.Взаимоблагоприятствование и сотрудничество в природе – случайность, экологическое сходство или эколого-биологическая закономерность.     


*Что почитать*   

Минимальный обязательный список чтения к семинару (на семинаре буду ждать знания этого материала):

1.Бигон М., Харпер Дж., Таунсенд К. Экология: особи, популяции, сообщества. Т.2. **Глава 18**.

2.Ипатов В.С., Кирикова Л.А., Мирин Д.М. Геоботаника. Глава 2 (разделы 2.2 – 2.4), **глава 3** 



## Тема   №2  Динамика экосистем: сукцессии и флуктуации

**Елена Михайловна Копцева** (*каф. Геоботаники*) ekoptseva[]hotmail.com



*Участники семинара идут  на кафедру геоботаники и встречаются с Е. М. Копцевой* 

- Адрес Кафедры геоботаники: Средний проспект В.О., д.41/43.


*Будут затронуты следующие вопросы*    

1. Причины изменения  экосистем. Циклические и направленные изменения. Виды динамики экосистем. Механизмы динамики экосистем, ее тренды и факторы, изменяющие ее. Влияние природных и антропогенных факторов на организацию и стабильность  экосистем.   

2. Сезонная изменчивость в экосистемах. Изменчивость в разных климатических зонах. Флуктуации. Цикличность экзогенетических процессов как причина флуктуаций. Ритмические погодные изменения и экологическая специфичность видов как причина флуктуаций.
Автогенные сукцессии. Система автогенных сукцессий.   

3. Инициальные сукцессии. Демутации как следствие эндогенеза. Понятие климакса. Роль деструкций в автогенных сукцессиях. Роль человека в сукцессиях. Участие животных. Климакс как динамическая система.    

4. Аллогенные сукцессии. Необратимость аллогенных сукцессий, как следствие экзогенеза.
Экотопические сукцессии. Роль климата, гидрологии, изменения поверхности земли. Способы обнаружения и анализа экотопических сукцессий.   

5. Деструкционные сукцессии. Влияние выпаса скота и сенокошения на сукцессию.
Модели сукцессий на семинарах обсуждаются на конкретных примерах и материалах. Рассматриваются параметры  экосистем, которые можно использовать для описания и оценки их состояния, а также для оценки влияния естественных и антропогенных факторов на  их организацию и стабильность   


*Что почитать*   

- Бигон М., Харпер Дж., Таунсенд К. Экология. Особи, популяции и сообщества. Том 1, 2.
- Ипатов В. С, Кирикова Л. А., Мирин Д. М.  Геоботаника: Учебник. —СПб.: Изд-во С.-Петерб. ун-та, 2010.  —117 с. (**Глава 7**).
- Онипченко В.Г. Функциональная фитоценология: Синэкология растений. Учебное пособие.М.:КРАСАНД, 2014. – 576 с. (**Глава 9**).


## Тема   №3 Приспособление водных организмов к среде обитания

**Дарья Вячеславовна Сафронова, Елена Николаевна Чернова** (*каф. Прикладной экологии*) dollydolly[]mail.ru, e.n.chernova[]yandex.ru

*Участники семинара идут на кафедру прикладной экологии и встречаются с Д. В. Сафроновой и Е. Н. Черновой* 

- Адрес Кафедры прикладной экологии: 16-я линия, д.29, 1 этаж.



*Будут затронуты следующие вопросы*    
1.Экологические группы гидробионтов   

2.Типы водных мест обитания   

3.Приспособления организмов к обитанию в толще воды, на дне, в поверхностной пленке воды, на погруженных субстратах   

4.Приспособления организмов к различным типам питания   

5.Приспособления организмов к переживанию неблагоприятных условий среды   

6.Диапазоны толерантности и их использование для оценки качества среды   

7.Биологические индексы для оценки качества водной среды    


*Что почитать*   

- Методы оценки качества вод по гидробиологическим показателям: учебно-методическая разработка по курсу «Гидробиология»; сост.: О.Ю. Деревенская. – Казань: КФУ, 2015. – 44 с.     
- Семерной, В. П. Общая гидробиология : текст лекций / Яросл. гос. ун-т, В. П. Семерной .— Ярославль : ЯрГУ, 2008 .— 184 с.      
- Бродский А.К. Краткий курс общей экологии. Учебное пособие. — СПб.: ДЕАН, 2000. - 224 с.      


*Опорный глоссарий*

- Экологический фактор – любой нерасчленяемый далее элемент среды, способный оказывать прямое или косвенное влияние на живые организмы хотя бы на протяжении одной из фаз их индивидуального развития [4]
- Экологическая группа - совокупность видов, характеризующаяся сходными потребностями в величине какого-либо экологического фактора и возникшими в результате его воздействия в процессе эволюции сходными признаками, закрепившимися в генотипе
- Лимнофилы – организмы, обитающие в стоячих водах (озерах, прудах, старицах и т.д.) [1]
- Реофилы – организмы, обитающие в текучих водах (реки, ручьи) [1]
- Пелофилы – обитатели илистых грунтов [1]
- Псаммофилы – обитатели песчаных грунтов [1]
- Литофилы – обитатели каменистых грунтов [1]
- Детрит – органические остатки умерших организмов [1]
- Сестон – (от греч. sestos — просеянный), название мелких планктонных организмов и взвешенных в воде неорганических и органических (детрит) частиц, т. е. всё, что улавливается мелкоячеистой планктонной сеткой [3]
- Планктон – организмы, населяющие толщу воды, не способные противостоять силам движения воды.
- Нектон - организмы, населяющие толщу воды, способные противостоять силам движения воды и контролировать своё местоположение в воде благодаря активному движению.
- Бентос – водные организмы, обитающие в грунте или на его поверхности [1]
- Перифитон – водные организмы, обитающие на выступающих участках дна, на камнях, корягах и других погруженных объектах, организмы-обрастатели [1]
- Нейстон - совокупность микроскопических и мелких организмов, прикрепляющихся к поверхностной плёнке воды за счёт силы поверхностного натяжения, передвигающихся по ней сверху (эпинейстон) или снизу (гипонейстон).
- Плейстон – это организмы крупных и средних размеров, часть тела которых погружена в воду, а часть выступает над ней.
- Макрофиты – высшие водные растения и некоторые крупные водоросли [1]
- Стенобионты – виды, особи которых устойчивы лишь к небольшим отклонениям значений фактора от оптимума [4]
- Эврибионты – виды, особи которых способны выдерживать значительные изменения фактора [4]
- Сапробность – (от греч. sapros – гнилой) – характеристика химических и биологических изменений в водной экосистеме при антропогенном загрязнении водоема биогенными и органическими веществами, как правило, не оказывающими токсического воздействия (по Пантле, Буку, 1955, в модификации Сладечека, 1973) [2]
- Трофность – (от греч. trophe – пища, питание) – это характеристика водоема по его биологической продуктивности, обусловленной содержанием биогенных веществ (соединения азота, фосфора и др.) и количественными показателями водных организмов, в первую очередь – автотрофных.
- Видовое разнообразие слагается из двух компонентов: компонента многообразия, связанного с видовым богатством) и выравненности распределения особей между видами.
- Видовое богатство – число видов в сообществе [4]
- Выравненность – равномерность распределения видов по их обилию в сообществе.
- Биоиндикация – метод оценки абиотических и биотических факторов среды обитания при помощи биологических систем (живых организмов) [1].
- Биоиндикаторы – организмы или сообщества организмов, жизненные функции которых так тесно коррелируют с некоторыми факторами среды, что могут применяться для их оценки [1].
- Биотестирование – один из приемов исследования в водной токсикологии, который используется для определения степени повреждающего действия химических веществ, потенциально опасных для гидробионтов, в контролируемых экспериментальных или полевых условиях путем регистрации изменений биологически значимых показателей (тест-функций) используемых тест-объектов, с последующей оценкой их состояния в соответствии с выбранным критерием точности [1].

*Ссылки*     
1. Основы экогеологии, биоиндикации и биотестирования водных экосистем / Под ред. В.В. Куриленко: Учеб.пособие. – СПб.: С.-Петерб. ун-та, 2004. – 448 с.     
2. Бабич С.В., Е.А. Новикова. Оценка состояния пресноводных водоемов. Экологические экскурсии. СПб., 2000. – 17 с.     
3. Биологический энциклопедический словарь Гл. ред. М. С. Гиляров; Редкол.: А. А. Бабаев, Г. Г. Винберг, Г. А. Заварзин и др. — 2-е изд., исправл. — М.: Сов. Энциклопедия, 1986    
4. Бродский А.К. Общая экология: учебник для студ.высш. учеб. заведений. – М.: Издательский центр «Академия», 2006 – 256 с.    



## Тема   №4 Эволюционные экологические адаптации

**Станислав Игоревич Мельницкий** (*каф. Энтомологии*)  simelnitsky[]gmail.com

*Участники семинара идут на кафедру энтомологии и встречаются  с С. И. Мельницким* 

- Адрес Кафедры энтомологии: В здании, где располагается Менделеевский научный центр (надо обогнуть кафедру Генетики).



*Будут затронуты следующие вопросы*

Фенотипическая пластичность как адаптация. Норма реакции организма как характеристика возможностей его фенотипической адаптации к действию экологических факторов. Стратегии фенотипической адаптации организмов к изменению экологических факторов: избегание, конформизм, регуляция, активное изменение среды обитания. Поведенческие адаптивные реакции. Выбор и предпочтение местообитаний у животных. Принцип зональной смены стаций Бей-Биенко. Суточные, лунные и годичные ритмы поведения. Физиологические адаптивные реакции. Акклимация и акклиматизация. Спячка, диапауза и другие сезонные физиологические адаптации. Морфогенетические адаптивные реакции. Полифенизм как защита от хищников, полифенизм, связанный с питанием, миграциями, сезонный полифенизм, социальный полифенизм у общественных насекомых.Различные формы мимикрии. Мюллеровская мимикрия и бейтсовская мимикрия.

 

*Что почитать*

- Бигон М., Харпер Дж., Таунсенд К. Экология. Особи, популяции и сообщества. Москва. Мир. 1989. Том 1, **С. 57–63, 156–168**.

- Карпентер Г.Д.Х., Форд Э. Б., Мимикрия. Москва-Ленинград. 1935. 109 стр.

- Кипятков В.Е. Мир общественных насекомых. Издательство ЛГУ 1991. **С. 167–201**.

- Риклефс Р. Основы общей экологии. Москва. Мир 1979. **С. 193-211**.

- Иорданский Н. Н. Фенотипическая пластичность организмов и эволюция. Журнал общей биологии 70, № 1, 2009, **С. 3–9**.


## Тема   №5  Взаимоотношения симбионтов и хозяев

**Владимр Александрович Крапивин, Анна Георгиевна Гончар**  (*каф. Зоологии беспозвоночных*) tanitolkai[]gmail.com, anya.gonchar[]gmail.com


*Участники семинара идут на кафедру Зоологии позвоночных (в лекционный зал) и встречаются с В. А. Крапивиным и А.Г.Гончар*

- Адрес Кафедры зоологии позвоночных: Главное здание, рядос с аудиторией 143


*Будут затронуты следующие вопросы*

1. Понятие симбиотических отношений, их типы и критерии классификации: термины и примеры. Как очертить границы паразитизма.

2. Взаимодействие симбионтов: понятие вреда, практические способы его оценки. Примеры взаимодействия паразитов и хозяев на уровне особей.

3. Взаимодействие паразитов и хозяев на популяционном уровне, компенсаторные механизмы и неожиданные эффекты.

4. Роль паразитов в сообществах.

Вторая половина семинара будет посвящена работе в группах над разбором реального исследования роли паразита в прибрежном сообществе.

**Для подготовки к семинару нужно познакомиться со следующими материалами:**

- Гранович А. И. От систем паразит–хозяин к паразитарным системам. Взаимодействие моллюсков рода Littorina с паразитирующими в них трематодами //Зоологический журнал. – 2016. – Т. 95. – №. 3. – С. 252-266. [pdf](Literature//Granovitch2016.pdf)

- Фокина Н. Н. и др. Оценка липидного состава и некоторых компонентов антиоксидантной системы мидий Mytilus edulis в условиях экспериментального заражения метацеркариями himasthla elongata //Труды Карельского научного центра Российской академии наук. – 2018. – №. 6. [pdf](Literature//Fokina_et_al2018.pdf)

- Приложения к Трудам ЗИН Том 320 (Приложение 4), 2016. К.В. Галактионов (Ред.) Коэволюция паразитов и хозяев.  https://www.zin.ru/journals/trudyzin/doc/vol_320_s4/TZ_320_4_Supplement_Glossary.pdf

Если есть вопросы, то связывайтесь с преподавателями!


*Опорный глоссарий для семинара*     
- Комменсализм (commensalism) – симбиоти-ческая ассоциация, безразличная для хозяина, но полезная для симбионта (см. симбиоз)

- Мутуализм (mutualism) – симбиотическая взаимовыгодная ассоциация между симбионтом и хозяином (см. симбиоз, симбионт).

- Облигатный симбионт (obligate symbiont) – как минимум часть жизненного цикла симбионта протекает на/в хозяине (см. симбиоз, симбионт).

- Паразит (parasite) – организм, находящийся в антагонистическом симбиозе с другим живым организмом, которого он использует в качестве источника пищи, среды обитания, и на которого частично или полностью возлагает регуляцию своих отношений с внешней средой (см. сим биоз).

- Паразитоид (parasitoid) – паразитический организм, обязательно вызывающий гибель хозяина (применим преимущественно к насекомым).

- Симбиоз (symbiosis) – облигатная или факультативная форма сожительства двух разноименных организмов.

- Симбионт (symbiont or symbiote) – зависимый член симбиотической ассоциации, использующий ресурс(ы), предоставляемые хозяином (см. симбиоз, хозяин).

- Факультативный симбионт (facultative sym-biont) – весь жизненный цикл симбионта может протекать вне хозяина.

- Хозяин (host) – член симбиотической ассоциации, предоставляющий ресурс симбионту (см. симбиоз, симбионт)

- Приспособленность (fitness) — количественное представление естественного отбора. Например, количество потомков, оставляемых особью.



## Тема   №6 Температура и живые системы: эксперименты, модели, практическое значение   

**Дмитрий Александрович Кучеров** (*каф. Энтомологии*),  cyathus[]yandex.ru

*Участники семинара идут на кафедру генетики (аудитория Г15) и встречаются с Д. А. Кучеровым* 

- Адрес Кафедры генетики: Рядом с кафедрой ботаники.


*Что почитать*   

- Бигон М., Харпер Дж., Таунсенд К. 1989. Экология. Особи, популяции и сообщества, т. 1. М.: Мир, стр. 65–92.
- Медведков А., 2016. Как глобальное потепление меняет природу сибирской тайги? Природа, №12.  https://elementy.ru/nauchno-populyarnaya_biblioteka/433987/Kak_globalnoe_poteplenie_menyaet_prirodu_sibirskoy_taygi
- Медников Б. М., 1977. Температура как фактор развития. В книге: «Внешняя среда и развивающийся организм», М.: Наука, стр. 7-8 и 12-14. [pdf](Task//Mednikov1977.pdf)
- Шмальгаузен, И. И., 1968. Факторы эволюции. Теория стабилизирующего отбора. М.: Наука, стр. 21-25 и 282-288.     

*Глоссарий*

- Гомойотермные организмы – организмы, поддерживающие относительно постоянную температуру тела, независимо от колебаний температуры в окружающей среде.
- Изотерма — воображаемая линия, соединяющая точки земной или водной поверхности с одной и той же средней температурой за определённый период (чаще всего январь или июль).
- Нижний температурный порог развития – условная температура, ниже которой процессы развития считаются остановившимися. 
- Модификационная (средовая) изменчивость – изменения фенотипа, вызванные действием экологических факторов.
- Норма реакции – характер и пределы изменений фенотипа в зависимости от значения того или иного фактора среды.
- Пойкилотермные организмы – организмы, температура тела которых изменяется вслед за колебаниями температуры окружающей среды.
- Сумма градусо-дней (сумма «эффективных температур») – сумма среднесуточных температур, превышающих нижний порог, необходимая организму для достижения определённой стадии развития (цветения растений, окукливания личинок насекомых и т.п.). Обратная величина коэффициента термолабильности.
- Термолабильность – свойство организмов изменять скорость жизненных процессов при изменении температуры.
- Фенотипическая пластичность – способность организма отвечать на воздействия и сигналы окружающей среды изменениями своей структуры, состояния, физиологии, движения и поведения.
- Эктотермы – организмы, температура тела которых в основном зависит от внешних источников тепла.
- Эндотермы – организмы, температура тела которых в основном зависит от внутренней теплопродукции.


**Задание для подготовки к семинару**

Группа должна ражделиться на две более или менее равные по численности компании. Каждая компания берет одно из практических заданий, которые описаны в файле [Задания по теме 6.docx](Task//Задания по теме 6.docx) 

- [Задание](Task//Задания по теме 6.docx)
- [Данные для работы](Task//Thermal_database.xls)

Внимание! Желательно результаты работы принести на флэшке, а еще лучше послать эти результаты накануне семнара Дмитрию Александровичу.

Не бойтесь выходить на связь с преподавателем! Хорошая работа на семинарах принесет повышение оценки за контрльные и домашние работы.

